### ISSUE TITLE
java.security.UnrecoverableKeyException: Cannot recover key

### ISSUE THREAD

**Issue by xyloman** [spring-cloud/spring-cloud-config#102]
When following the documentation http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_creating_a_key_store_for_testing I ran into an issue where a cannot recover key exception is thrown when the KeyStoreKeyFactory class attempts to read the key from the JKS.  

```
Caused by: java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:138)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:55)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at org.springframework.security.rsa.crypto.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:57)
```

I was able to work around the issue by modifying the keytool command to as follows:

```
keytool -genkeypair -alias mytestkey -keyalg RSA \
   -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" \
   -keypass changeme -keystore server.jks -storepass changeme
```

And then modified the application.yml config to the following

```
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: changeme
    alias: mytestkey
```

**Comment by dsyer** [comment]
Duplicates #98
