### ISSUE TITLE
Error creating bean and crashed in JPA multi datasource when integrated Spring Cloud Config Client

### ISSUE THREAD

**Issue by LuoLee** [spring-cloud/spring-cloud-config#1026]
When we using spring cloud config client in my multi datasource jpa project, it complains and crashed:
**I also create a demo project [LuoLee/jpa-with-spring-cloud-config](https://github.com/LuoLee/jpa-with-spring-cloud-config) and the config file using git here [jpaconfig-dev.yml](https://coding.net/u/testusera/p/config-server/git/blob/master/UNI-Config-Server/subDir/jpaconfig-dev.yml?public=true)**
```
2018-05-29 11:30:04.105  INFO 17908 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2018-05-29 11:30:04.233  WARN 17908 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'primaryDatasourceController': Unsatisfied dependency expressed through field 'userDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'primaryUserDao': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Not a managed type: class me.luolee.jpawithspringconfig.entity.pri.PrimaryUser
2018-05-29 11:30:04.233  INFO 17908 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2018-05-29 11:30:04.247  INFO 17908 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2018-05-29 11:30:04.249  INFO 17908 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-05-29 11:30:04.374  INFO 17908 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-05-29 11:30:04.383 ERROR 17908 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'primaryDatasourceController': Unsatisfied dependency expressed through field 'userDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'primaryUserDao': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Not a managed type: class me.luolee.jpawithspringconfig.entity.pri.PrimaryUser
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1268) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at me.luolee.jpawithspringconfig.JpaWithSpringCloudApplication.main(JpaWithSpringCloudApplication.java:16) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'primaryUserDao': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Not a managed type: class me.luolee.jpawithspringconfig.entity.pri.PrimaryUser
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.16.RELEASE.jar:4.3.16.RELEASE]
...goes on...
```
The `PrimaryDataSourceConfiguration` file show on:
```
package me.luolee.jpawithspringconfig.config;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.jdbc.DataSourceBuilder;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import javax.persistence.EntityManagerFactory;
import javax.sql.DataSource;

@Configuration
@EnableTransactionManagement
@EnableJpaRepositories(
		entityManagerFactoryRef = "primaryEntityManager",
		transactionManagerRef = "primaryTransactionManager",
		basePackages = "me.luolee.jpawithspringconfig.dao.pri"
)
public class PrimaryDataSourceConfiguration {

	/**
	 * MySQL datasource definition.
	 *
	 * @return datasource.
	 */
	@Bean
	@Primary
	@ConfigurationProperties(prefix = "spring.datasource")
	public DataSource dataSource() {
		return DataSourceBuilder
					.create()
					.build();
	}

	/**
	 * Entity manager definition.
	 *
	 * @param builder an EntityManagerFactoryBuilder.
	 * @return LocalContainerEntityManagerFactoryBean.
	 */
	@Bean(name = "primaryEntityManager")
	@Primary
	public LocalContainerEntityManagerFactoryBean primaryEntityManagerFactory(EntityManagerFactoryBuilder builder) {
		return builder
					.dataSource(dataSource())
					.packages("me.luolee.apimultidatasource.entity.pri")
					.build();
	}

	/**
	 * @param entityManagerFactory
	 * @return
	 */
	@Bean(name = "primaryTransactionManager")
	@Primary
	public PlatformTransactionManager primaryTransactionManager(@Qualifier("primaryEntityManager") EntityManagerFactory entityManagerFactory) {
		return new JpaTransactionManager(entityManagerFactory);
	}
}
```
`PrimaryUserDao` show here:
```
public interface PrimaryUserDao extends JpaRepository<PrimaryUser, Long> {

    PrimaryUser findById(Long id);
}
```
`PrimaryUser` entity:
```
@Entity
@Table(name = "USER")
@EntityListeners(AuditingEntityListener.class)
public class PrimaryUser implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    private String username;

    @NotBlank
    private String password;

    public PrimaryUser() {
    }

    public PrimaryUser(String username, String password) {
        this.username = username;
        this.password = password;
    }

    // Getter, Setter and toString
}
```
`PrimaryDatasourceController`:
```
@RestController
@RequestMapping("/primary")
public class PrimaryDatasourceController {

    private static final Logger logger = LoggerFactory.getLogger(PrimaryDatasourceController.class);

    @Autowired
    private PrimaryUserDao userDao;

    @GetMapping("/{id}")
    public ResponseEntity<PrimaryUser> fetchUserById(@PathVariable String id) {
        PrimaryUser user = userDao.findById(Long.parseLong(id));
        return ResponseEntity.ok(user);
    }

}
```

And it compiles and runs OK if I comment the multi datasource config in my [PrimaryDataSourceConfiguration](https://github.com/LuoLee/jpa-with-spring-cloud-config/blob/master/src/main/java/me/luolee/jpawithspringconfig/config/PrimaryDataSourceConfiguration.java) and [SecondDataSourceConfiguration.java](https://github.com/LuoLee/jpa-with-spring-cloud-config/blob/master/src/main/java/me/luolee/jpawithspringconfig/config/SecondDataSourceConfiguration.java), and [@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})](https://github.com/LuoLee/jpa-with-spring-cloud-config/blob/master/src/main/java/me/luolee/jpawithspringconfig/JpaWithSpringCloudApplication.java) in my main class.(If so, the demo project will run in **SINGLE** datasource and Spring Cloud Config).

Does some wrong in my DataSourceConfiguration or some else ?

**Comment by spencergibb** [comment]
What makes you think there is a problem with spring cloud config? Your exception doesn't include it.

**Comment by LuoLee** [comment]
Yes, I had post on StackOverflow for Spring Data JPA.
Thanks a lot.
