### ISSUE TITLE
@RefreshScope doesn't work with conditional DataSource definition

### ISSUE THREAD

**Issue by ericdahl** [spring-cloud/spring-cloud-config#105]
(note: updating issue from original, as I realized I missed part of documentation)

With spring-boot, if I define a ```DataSource``` bean with ```@RefreshScope``` it cause spring-boot's ```@ConditionalOnBean(DataSource.class)``` to not work. This means that two beans are created. It is supposed to only create the standard spring-boot version if I haven't defined a DataSource myself. This used to work with ```1.0.0.RC3``` but stopped working with ```1.0.0.RELEASE```.

A simplified test case can be found at https://github.com/ericdahl/spring-boot-config-datasource-test/ (just clone,  ```mvn spring-boot:run``` and load http://localhost:8080/health)

```java
@RefreshScope
@Configuration
public class DataSourceConfig {

    @RefreshScope
    @Bean
    public DataSource customDataSource() {
        final String url = "jdbc:h2:mem:customDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE";

        LOGGER.info("Creating in-memory h2 database with jdbc url [{}]", url);
        return DataSourceBuilder
                .create()
                .driverClassName(EmbeddedDatabaseConnection.H2.getDriverClassName())
                .url(url)
                .username("sa")
                .password("")
                .build();

    }
}
```

![health](https://cloud.githubusercontent.com/assets/4712580/6649956/75feb370-c9b7-11e4-98f8-28212654f058.png)

I'm guessing it's related to how spring-boot utilizes conditional bean definitions.

**Comment by dsyer** [comment]
I don't think `@RefreshScope` on a `@Configuration` works and it might be the thing that breaks your app. There is something more complicated going on though because if I add your `DataSourceConfig` to an existing app I get a more nasty autowiring error:

```
d by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.sql.DataSource org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer.dataSource; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'customDataSource': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 41 more
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'customDataSource': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
...
```

**Comment by dsyer** [comment]
Probably the same issue as this SO question: http://stackoverflow.com/questions/28610353/spring-boot-with-session-based-data-source/28626486#28626486

**Comment by ericdahl** [comment]
@dsyer 

That ```BeanCurrentlyInCreationException``` also happens in the example project I posted if I remove the ```@RefreshScope``` from the Configuration class (while leaving it on the ```@Bean```).

Similarly, this didn't error in 1.0.0-RC3

**Comment by dsyer** [comment]
I think this needs to be fixed in Spring Boot (https://github.com/spring-projects/spring-boot/issues/2658). We'll bump to Boot 1.2.3 in Spring Cloud Config 1.0.1.

**Comment by dsyer** [comment]
Spring Boot 1.2.3 is out now so this is fixed.
