### ISSUE TITLE
spring.profiles.active in properties file can't contain other variables

### ISSUE THREAD

**Issue by bgiaccio** [spring-cloud/spring-cloud-config#1097]
We are upgrading from spring cloud Dalston.RELEASE  to Finchley.RELEASE
Which moved the spring-cloud-config from 1.3.0 to 2.0.0

We have a file foo.properties
```
profileList=A, B, C
spring.profiles.active=${profileList}
```
In 1.3 calling `curl http://localhost:8383/foo/bob`  the data returns properly
Same call with 2.0 we get 
```
java.lang.IllegalArgumentException: Could not resolve placeholder 'profileList' in value "${profileList}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.boot.context.properties.bind.PropertySourcesPlaceholdersResolver.resolvePlaceholders(PropertySourcesPlaceholdersResolver.java:60)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.convert(IndexedElementsBinder.java:142)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:84)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:70)
	at org.springframework.boot.context.properties.bind.ArrayBinder.bindAggregate(ArrayBinder.java:46)
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:58)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:306)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:442)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$100(Binder.java:382)
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:305)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:263)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221)
	... 106 common frames omitted
Wrapped by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.profiles.active' to java.lang.String[]
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:250)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:226)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:210)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:166)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:153)
```

If we change **spring.profiles.active**  to any other variable it works just fine.  So I'm assuming some change caused is treating that property differently

**Comment by spencergibb** [comment]
I'm unable to replicate the problem. 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
