### ISSUE TITLE
Yml endpoint error

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-config#1113]
Config server build from initiazer using `spring-boot-starter-parent:2.0.4.RELEASE`.

Having these files packed into an app and run with `native` profile.
```
$ cat src/main/resources/config/foo.properties 
foo: from foo props
democonfigclient.message: hello spring io

$ cat src/main/resources/config/foo-db.properties 
foo.db: mycooldb

$ cat src/main/resources/config/foo-development.properties 
bar: spam
foo: from foo development

$ cat src/main/resources/config/foo-development-db.properties 
combined: true
```

Using `properties` endpoint works but `yml` errors out:
```
$ curl localhost:8888/foo-db.properties
democonfigclient.message: hello spring io
foo: from foo props
foo.db: mycooldb

$ curl localhost:8888/foo-db.yml
{"timestamp":"2018-08-20T07:01:13.249+0000","status":500,"error":"Internal Server Error","message":"java.lang.String cannot be cast to java.util.Map","path":"/foo-db.yml"}
```

With error on a server side.

```
2018-08-20 10:01:13.247 ERROR 19223 --- [nio-8888-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map] with root cause

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.cloud.config.server.environment.EnvironmentController$PropertyNavigator.setMapValue(EnvironmentController.java:367) ~[spring-cloud-config-server-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.config.server.environment.EnvironmentController$PropertyNavigator.access$100(EnvironmentController.java:349) ~[spring-cloud-config-server-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.config.server.environment.EnvironmentController.convertToMap(EnvironmentController.java:240) ~[spring-cloud-config-server-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.config.server.environment.EnvironmentController.labelledYaml(EnvironmentController.java:204) ~[spring-cloud-config-server-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.config.server.environment.EnvironmentController.yaml(EnvironmentController.java:193) ~[spring-cloud-config-server-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
```
Maybe we should handle these cases with yml where we have `foo` and `foo.db` in props.

**Comment by spencergibb** [comment]
It's not valid yaml, there's nothing we can do here.

```
foo: value
  db: value
```

**Comment by jvalkeal** [comment]
@spencergibb I know it's not valid and I proposed to handle this error some other way that just blindly throwing that error. It's impossible from a stack to know what is wrong.

**Comment by OlgaMaciaszek** [comment]
An `ExceptionAnalyzer` should be added for that.

**Comment by iskradelta** [comment]
This bug triggers on perfectly valid yaml and configuration useable by spring boot alone.
