### ISSUE TITLE
I use config server with JDBC but it's not effective and  always use  git 

### ISSUE THREAD

**Issue by SimpleChenyh** [spring-cloud/spring-cloud-config#1128]
Question

I use config server with JDBC but it's not effective and  always use  git ,I will get the  ‘You need to configure a uri for the git repository“ exception information.

Bug report

```java
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthEndpoint]: Factory method 'healthEndpoint' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configServerHealthIndicator' defined in class path resource [org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.class]: Unsatisfied dependency expressed through method 'configServerHealthIndicator' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.config.server.config.CompositeConfiguration': Unsatisfied dependency expressed through method 'setEnvironmentRepos' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultEnvironmentRepository' defined in class path resource [org/springframework/cloud/config/server/config/DefaultRepositoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: You need to configure a uri for the git repository
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    ... 49 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthEndpoint]: Factory method 'healthEndpoint' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configServerHealthIndicator' defined in class path resource [org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.class]: Unsatisfied dependency expressed through method 'configServerHealthIndicator' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.config.server.config.CompositeConfiguration': Unsatisfied dependency expressed through method 'setEnvironmentRepos' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultEnvironmentRepository' defined in class path resource [org/springframework/cloud/config/server/config/DefaultRepositoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: You need to configure a uri for the git repository
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.createEndpointBean(EndpointDiscoverer.java:143) ~[spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.createEndpointBeans(EndpointDiscoverer.java:132) ~[spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.discoverEndpoints(EndpointDiscoverer.java:122) ~[spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.getEndpoints(EndpointDiscoverer.java:116) ~[spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration.servletEndpointRegistrar(ServletEndpointManagementContextConfiguration.java:46) ~[spring-boot-actuator-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$edfd7c95.CGLIB$servletEndpointRegistrar$0(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$edfd7c95$$FastClassBySpringCGLIB$$37871542.invoke(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$edfd7c95.servletEndpointRegistrar(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
    ... 50 common frames omitted
```
Enhancement
parent pom.xml
```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.0.1.RELEASE</version>
</parent>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Finchley.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.0.4</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.0.31</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
config-server-db pom.xml
```xml
<dependencies>
    <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-jdbc</artifactId>
        <exclusions>
            <exclusion>
                <groupId>com.zaxxer</groupId>
                <artifactId>HikariCP</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-config-server</artifactId>
    </dependency>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
</dependencies>
```
application.yml
```yml
server:
  port: 8888
spring:
  application:
    name: config-server-db
  profiles:
    active: jdbc
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/config?useUnicode=true&characterEncoding=UTF-8
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      server:
        default-label: master
        prefix: config
        jdbc:
          sql: SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?

```

The test configuration java file

```java
@Configuration
public class Config {
    @Value("${spring.profiles.active}")
    private  String env;
    @Bean
    @Profile("jdbc")
    @ConditionalOnClass(JdbcTemplate.class)
    public Object object(){
        // It will enter this method and print 'jdbc'
        System.out.println(env);
        return  null;
    }
}
```

It’s hard for me for a long time, I want to know what it is because of this? Thank you

**Comment by mjohns39** [comment]
If you add "native" to the spring.profiles.active property, it will tell spring cloud that you do not want to use a scm uri for your config.  You can then create beans to specify your jdbc connector and environment properties from that connector.  Keep in mind that some properties will still need to be set in application.yml and bootstrap.yml.

I'm not saying this is the best way to do it, but I think this would be at least one way to do it.  And I know adding "native" to your active profiles will remove that exception :)

**Comment by ryanjbaxter** [comment]
It looks like you POM is misconfigured, but it hard to tell.  Can you create a sample that reproduces the problem and either attach it as a zip to this issue or put it in gitgub?

**Comment by SimpleChenyh** [comment]
I have uploaded a zip to my google cloud drive,it's [here](https://drive.google.com/open?id=1qjoJKyPIwldrRTlhAk81ckbNlSYstvcI), I use this sample to find the problem
```java
@Configuration
public class Config {
    @Value("${spring.profiles.active}")
    private  String env;
    @Bean
    @Profile("jdbc")
    @ConditionalOnClass(JdbcTemplate.class)
    public Object object(){
        //when I use jetty it will enter this method and print 'jdbc',but use tomcat it not
        // I think it is caused by the loading logic.
        System.out.println(env);
        return  null;
    }
}
```
Thank you for your replay

**Comment by ryanjbaxter** [comment]
Yes there is some kind of extra configuration you must need to do to setup the `JdbcTemplate` when using MySQL.  I am not familiar enough to know what that is.  If you remove the MySQL dependency and add H2 to the classpath the apps starts fine.

**Comment by SimpleChenyh** [comment]
What puzzles me is that just changing the version to Edgware.SR4 is available, and also can use MySQL, What changes have been made in it? I don't quite understand the source code. But fortunately, there are other solutions.

**Comment by ryanjbaxter** [comment]
Maybe it was a change in how the `JdbcTemplate` is created between Boot versions?

**Comment by ronenmalka** [comment]
@SimpleChenyh Did you solve this issue?

**Comment by SimpleChenyh** [comment]
> @SimpleChenyh Did you solve this issue?

Seeing that there is no JdbcTemplate Bean, I tried to explicitly declare that the DataSource is working, and I am still looking for why the DataSource was not created in time.

```
@Bean
public DataSource dataSource(){
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("com.mysql.jdbc.Driver");
    dataSource.setUrl("xx");
    dataSource.setUsername( "xxx" );
    dataSource.setPassword( "xxxx" ); 
    return dataSource;
}
```

**Comment by ronenmalka** [comment]
I gave up...
Moved to H2 for storring configuration.

**Comment by SimpleChenyh** [comment]
@ronenmalka Explicitly declare datasource is not working for you?

**Comment by girish-jung** [comment]
hi @SimpleChenyh - i am getting the same issue with postgres as backend. So can you please tell me what was the final solution? It doesn't work with either defining a datasource or with version "Edgware.SR4"

**Comment by SimpleChenyh** [comment]
> hi @SimpleChenyh - i am getting the same issue with postgres as backend. So can you please tell me what was the final solution? It doesn't work with either defining a datasource or with version "Edgware.SR4"

Hi, I provide the example https://github.com/SimpleChenyh/config-server-jdbc-example/blob/bd4cda0f132338d46e60c0e748fdefdef56f1000/Finchley.SR4/pom.xml#L4-L22,

The problem is spring boot dependency version,When the spring-cloud-dependencies version is Finchley.SR1.
has a problem use below
```xml
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
       <version>2.0.1.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
</parent>
```
has no problem use below
```xml
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
       <version>2.0.3.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
</parent>
```
reference:
https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-dependencies/Finchley.SR1/pom, You can see the spring-cloud-dependencies-parent version is 2.0.3.RELEASE
