### ISSUE TITLE
Spring Cloud Config Client : RETRY not working

### ISSUE THREAD

**Issue by hiteshbargujar** [spring-cloud/spring-cloud-config#1139]
Bug report
I am following the documentation provided here http://cloud.spring.io/spring-cloud-static/spring-cloud.html#config-client-fail-fast

1. I have an App which is just a CloudConfigClient
properties file for it
```
spring.application.name=cloudconfigclient
server.port=8090
```

build.gradle
```
buildscript {
	ext {
		springBootVersion = '2.0.5.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.example.aws.sqs'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}


ext {
	springCloudVersion = 'Finchley.SR1'
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.cloud:spring-cloud-starter-config')
	compile group: 'org.springframework.retry', name: 'spring-retry', version: '1.0.3.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-aop', version: '2.0.5.RELEASE'
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}
```
Main Class
```
package com.example.aws.sqs;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@EnableAutoConfiguration
public class CloudConfigClientApplication {

	public static void main(String[] args) {
		SpringApplication.run(CloudConfigClientApplication.class, args);
	}
}
```
I am building and running the jar like this
```
java -jar -Dspring.cloud.config.failFast=true CloudConfigClient-0.0.1-SNAPSHOT.jar 
```

When the CloudConfigServer is not available, the application fails to start
```
2018-09-13 21:16:16.907  INFO 36463 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3ecf72fd: startup date [Thu Sep 13 21:16:16 EDT 2018]; root of context hierarchy
2018-09-13 21:16:17.150  INFO 36463 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$3f886f7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.5.RELEASE)

2018-09-13 21:16:17.353  INFO 36463 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2018-09-13 21:16:17.455  INFO 36463 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:8888. Will be trying the next url if available
2018-09-13 21:16:17.462 ERROR 36463 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:136) ~[spring-cloud-config-client-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) ~[spring-cloud-context-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:654) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at com.example.aws.sqs.CloudConfigClientApplication.main(CloudConfigClientApplication.java:12) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [CloudConfigClient-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [CloudConfigClient-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [CloudConfigClient-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [CloudConfigClient-0.0.1-SNAPSHOT.jar:na]
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8888/cloudconfigclient/default": Connection refused; nested exception is java.net.ConnectException: Connection refused
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:696) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:564) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigServicePropertySourceLocator.java:218) ~[spring-cloud-config-client-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:96) ~[spring-cloud-config-client-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	... 15 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_65]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_65]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_65]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_65]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_65]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_65]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_65]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_65]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_65]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_65]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_65]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_65]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_65]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_65]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:687) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	... 19 common frames omitted
```

RETRY is not attempted.

**Comment by spencergibb** [comment]
Is your config server running on localhost:8888? That is the default and you haven't told it otherwise.

Your error is Caused by: java.net.ConnectException: Connection refused

**Comment by hiteshbargujar** [comment]
yes I am using default localhost:8888, my expectation was if the server is unavailable a retry mechanism will try to get the config again. Is that not the right expectation?

**Comment by ryanjbaxter** [comment]
Please see the docs on this topic http://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#config-client-retry

You need to set `spring.cloud.config.fail-fast=true`

**Comment by hiteshbargujar** [comment]
@ryanjbaxter - I am doing that, I am passing it at runtime like this

`java -jar -Dspring.cloud.config.fail-fast=true CloudConfigClient-0.0.1-SNAPSHOT.jar`

**Comment by spencergibb** [comment]
I'm unable to reproduce the issue with a fresh project from start.spring.io. 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by hiteshbargujar** [comment]
[CloudConfigClient.zip](https://github.com/spring-cloud/spring-cloud-config/files/2389565/CloudConfigClient.zip)
[CloudConfigServer.zip](https://github.com/spring-cloud/spring-cloud-config/files/2389566/CloudConfigServer.zip)

Attached are the client and server code.

**Comment by spencergibb** [comment]
Letting the boot dependency plugin handle the versions fixed your issue.
Changing:
```
	compile group: 'org.springframework.retry', name: 'spring-retry', version: '1.0.3.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-aop', version: '2.0.5.RELEASE'
```
to 
```
	compile group: 'org.springframework.retry', name: 'spring-retry'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-aop'
```
