### ISSUE TITLE
Datasource Issue with Spring Boot 2.1.x

### ISSUE THREAD

**Issue by troyhart** [spring-cloud/spring-cloud-config#1142]
I have a very simple [spring boot JPA application](https://github.com/troyhart/spring-cloud-config-datasource-issue) that demonstrates an issue when mixing `spring-boot-starter-data-jpa` and `spring-cloud-starter-config` on spring boot version `2.1.0.M3`.

When I attempt to deploy the `master` branch of this project I get the follow error:

```
2018-09-15 11:56:16.748 [DEBUG] o.s.b.d.LoggingFailureAnalysisReporter : Application failed to start due to an exception

org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'dataSource' 
defined in BeanDefinition defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: 
Cannot register bean definition [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; 
lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; 
initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in class path resource 
[org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]] for bean 'dataSource': There is already 
[Root bean: class [null]; scope=refresh; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=false; 
primary=false; factoryBeanName=org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari; factoryMethodName=dataSource; 
initMethodName=null; destroyMethodName=(inferred); defined in class path resource 
[org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]] bound.
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:877) 
  ~[spring-beans-5.1.0.RC3.jar:5.1.0.RC3]
  at org.springframework.cloud.autoconfigure.RefreshAutoConfiguration$RefreshScopeBeanDefinitionEnhancer.postProcessBeanDefinitionRegistry(RefreshAutoConfiguration.java:140) 
  ~[spring-cloud-context-2.0.1.RELEASE.jar:2.0.1.RELEASE]
  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) 
  ~[spring-context-5.1.0.RC3.jar:5.1.0.RC3]
  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125) 
  ~[spring-context-5.1.0.RC3.jar:5.1.0.RC3]
  at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693) 
  ~[spring-context-5.1.0.RC3.jar:5.1.0.RC3]
  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:530) 
  ~[spring-context-5.1.0.RC3.jar:5.1.0.RC3]
  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) 
  ~[spring-boot-2.1.0.M3.jar:2.1.0.M3]
  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:797) [spring-boot-2.1.0.M3.jar:2.1.0.M3]
  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:421) [spring-boot-2.1.0.M3.jar:2.1.0.M3]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:340) [spring-boot-2.1.0.M3.jar:2.1.0.M3]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) [spring-boot-2.1.0.M3.jar:2.1.0.M3]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1279) [spring-boot-2.1.0.M3.jar:2.1.0.M3]
  at com.myco.DatasourceTestApplication.main(DatasourceTestApplication.java:10) [classes/:na]

2018-09-15 11:56:16.748 [ERROR] o.s.b.d.LoggingFailureAnalysisReporter : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dataSource', defined in BeanDefinition defined in class path resource 
[org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class], could not be registered. 
A bean with that name has already been defined in class path resource 
[org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

However, If I change the version of spring boot to `2.0.4.RELEASE` then the application deploys and works as expected. (see branch `sb-2.0.4.RELEASE`). Also, I can simply remove the dependency on `spring-cloud-starter-config` from the pom and leave the spring boot version at `2.1.0.M3` and there is no issue (see branch `sans-spring-cloud-starter-config`). 

Thanks!

Troy

**Comment by spencergibb** [comment]
Finchley is not compatible with boot 2.1.0. we will be releasing a Greenwich milestone next week

**Comment by cpaika** [comment]
Thanks Spencer!

**Comment by HopscotchSen** [comment]
Greenwich.M1 and boot 2.1.0 still have probleam.

**Comment by HopscotchSen** [comment]
@spencergibb

**Comment by ryanjbaxter** [comment]
Use Greenwich.BUILD-SNAPSHOT

**Comment by leoamp** [comment]
@spencergibb I am also running into similar issue, despite of using Greenwich.BUILD-SNAPSHOT

org.springframework.boot:spring-boot-starter-parent:2.1.0.RELEASE
org.springframework.cloud:spring-cloud-sleuth:2.0.3.BUILD-SNAPSHOT
org.springframework.cloud:spring-cloud-dependencies:Greenwich.BUILD-SNAPSHOT

and here is the log:

> {"thread":"main","level":"ERROR","loggerName":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","message":"\r\n\r\n***************************\r\nAPPLICATION FAILED TO START\r\n***************************\r\n\r\nDescription:\r\n\r\nThe bean 'dataSource', defined in BeanDefinition defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class] and overriding is disabled.\r\n\r\nAction:\r\n\r\nConsider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true\r\n","endOfBatch":false,"loggerFqcn":"org.apache.commons.logging.impl.SLF4JLocationAwareLog","instant":{"epochSecond":1542303701,"nanoOfSecond":906000000},"contextMap":{},"threadId":1,"threadPriority":5,"source":{"class":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","method":"report","file":"LoggingFailureAnalysisReporter.java","line":42}}

Any pointers?

**Comment by spencergibb** [comment]
Sleuth 2.0.x is not compatible with Greenwich

**Comment by leoamp** [comment]
Thanks for the pointer @spencergibb 
I referred this: https://github.com/spring-cloud/spring-cloud-release/blob/master/spring-cloud-dependencies/pom.xml and replaced the version for Sleuth to 2.1.0.BUILD-SNAPSHOT and all errors gone for now.

**Comment by spencergibb** [comment]
You should not use individual versions and should use the BOM.

**Comment by leoamp** [comment]
I would be nice if you can give me an example @spencergibb Thanks. 
P.S: This is something new for me.

**Comment by leoamp** [comment]
Thanks @ryanjbaxter. I did try that and got to know what Spencer was referring to. Thanks.

**Comment by larsduelfer** [comment]
Hi there, may I ask why this issue is closed? As far as we are currently experiencing, the problem still occurs.

**Comment by spencergibb** [comment]
We close issues when they are fixed. You either have to wait until the next release (today) or use snapshots.

**Comment by rhandsch** [comment]
I've solved the issue by adding a DataSource bean manually like:
```
    @Bean
    public DataSource dataSource(DataSourceProperties dataSourceProperties) {
        return dataSourceProperties.initializeDataSourceBuilder().build();
    }
```
This info might be of interest for those who don't want to wait for a Greenwich release.

**Comment by mziemba** [comment]
I also had this issue, cannot reproduce it anymore using Greenwich.M2

**Comment by kbreczko** [comment]
Spring Boot 2.1.x disables the overrides of this type of bean by default.  Try adding the following line to the application properties:
`spring.main.allow-bean-definition-overriding=true`
This re-enables the previous behavior.

**Comment by larsduelfer** [comment]
We are now also using Greenwich.M2 - that solved the issue for us as well.

**Comment by onacit** [comment]
Confirm. `Greenwich.RC2` has no problem.

**Comment by liyz1218** [comment]
I still don't understand the specific problem, can you explain it in more detail

**Comment by cecchisandrone** [comment]
It still happens with Spring Boot 2.1.2 and Spring Cloud Greenwich.RELEASE.

**Comment by lxzchen** [comment]
config > spring.main.allow-bean-definition-overriding=true work well.

**Comment by mlecar** [comment]
> config "spring.main.allow-bean-definition-overriding=true" work well.

Yes, but this can take you to other issues that may be hard to track.
In my case I was using spring-boot:2.1.4 and spring-cloud-config-aws-kms:3.1, which was using spring-cloud-context:2.0.1.

I switched to spring-cloud-config-aws-kms:4.1, which is using spring-cloud-context:2.1.1 and this issue has gone.
