### ISSUE TITLE
Finchley.SR2 keystore Startup errors

### ISSUE THREAD

**Issue by hero-zhanghao** [spring-cloud/spring-cloud-config#1176]
I upgraded the version of spring cloud from finchley.sr1 to finchley.sr2, and the version of spring boot was upgraded from 2.0.4.release to 2.0.6.release. When starting the config project, I got the following error:

```
java.lang.IllegalStateException: Cannot decrypt: key=spring.security.user.password
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:202)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:166)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:96)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener$DelegatingEnvironmentDecryptApplicationInitializer.initialize(BootstrapApplicationListener.java:424)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:628)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:364)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
	at com.mchain.module.config.ConfigServerApplication.main(ConfigServerApplication.java:14)
Caused by: java.lang.IllegalStateException: Cannot load keys from store: class path resource [config-server.keystore]
	at org.springframework.security.rsa.crypto.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:76)
	at org.springframework.cloud.config.server.encryption.KeyStoreTextEncryptorLocator.locate(KeyStoreTextEncryptorLocator.java:84)
	at org.springframework.cloud.config.server.encryption.LocatorTextEncryptor.decrypt(LocatorTextEncryptor.java:52)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:194)
	... 9 common frames omitted
Caused by: java.security.KeyStoreException: keystore not found
	at java.security.KeyStore.getInstance(KeyStore.java:851)
	at org.springframework.security.rsa.crypto.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:64)
	... 12 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: keystore KeyStore not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	... 13 common frames omitted
```
The error showed that the keystore file could not be found, but it was in our project path and the bootstrap.yml configuration was as follows:
```
encrypt:
  key-store:
    location: classpath:/config-server.keystore
    alias: config-server
    password: test
    secret: test
```
After I reset spring cloud and spring boot versions back to previous versions, the project was running normally, and I compared the finchley.sr1 and finchley.sr2 keystore documents without seeing any changes.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by hero-zhanghao** [comment]
As before, when I downgraded the versions to finchley.sr1 and 2.0.4.release, that exception did not appear in either configuration at startup.

**Comment by hero-zhanghao** [comment]
Yes, it's the name, the suffix, exactly. After I changed the file name of config-server.keystore to config-server.jks, that exception did not appear at startup.

**Comment by ryanjbaxter** [comment]
Even when I use boot 2.0.4 and Finchley.SR1 the app still wont start for me

**Comment by hero-zhanghao** [comment]
Is not the case, because this is one of the most simple repetition error demo, should pay attention to is the 

> Java.security.KeyStoreException: keystore not found

 this exception, when using the boot 2.0.4 and Finchley. SR1, won't appear when using server.jks also won't appear, because project configuration issue, is not to be in full swing.

If you need a normal demo that doesn't show an exception, I can provide it.
