### ISSUE TITLE
Unable to pull git repo, remote hung up unexpectedly.

### ISSUE THREAD

**Issue by yi-ge** [spring-cloud/spring-cloud-config#1205]
My config:
```
spring:
  application:
    name: xiao-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lvpinhui/xiao-config-repo.git
          force-pull: true # Force pull in Git Repositories
          ignoreLocalSshSettings: true
          hostKey: "AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
          hostKeyAlgorithm: ssh-rsa
          strictHostKeyChecking: false
          basedir: /Users/wangyi/Downloads/test
          privateKey: |
          xxx
```

I can;t pull git repo:

```
org.eclipse.jgit.api.errors.TransportException: git@github.com:lvpinhui/xiao-config-repo.git: remote hung up unexpectedly
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:254) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar:5.1.3.201810200350-r]
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar:5.1.3.201810200350-r]
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar:5.1.3.201810200350-r]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:574) [spring-cloud-config-server-2.1.0.M3.jar:2.1.0.M3]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.copyRepository(JGitEnvironmentRepository.java:549) [spring-cloud-config-server-2.1.0.M3.jar:2.1.0.M3]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:532) [spring-cloud-config-server-2.1.0.M3.jar:2.1.0.M3]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:261) [spring-cloud-config-server-2.1.0.M3.jar:2.1.0.M3]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:240) [spring-cloud-config-server-2.1.0.M3.jar:2.1.0.M3]
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:150) [spring-cloud-config-server-2.1.0.M3.jar:2.1.0.M3]
```

**Comment by spencergibb** [comment]
It's a remote error. I don't know how much we can help since it looks like you're going against a private repository

**Comment by yi-ge** [comment]
@spencergibb Yes, I use a private repository. I can pull in server, but spring cant. The log show `remote hung up unexpectedly`.

**Comment by yi-ge** [comment]
It is wrong with my mac, but it is well in the Cent OS.
