### ISSUE TITLE
Spring Boot cipher BadPaddingException: Decryption error

### ISSUE THREAD

**Issue by adnanmian** [spring-cloud/spring-cloud-config#1210]
I am using **Spring Boot 1.5.18.RELEASE** and I added the **Spring Cloud Config Server (1.4.5.RELEASE)** to the same Spring Boot project, so I can add encrypted properties in the application.properties file.

First I used the **symmetric key** and set the value of **encrypt.key** in bootstrap.properties,

- I can **encrypt** or **decrypt** by making POST call to "http://localhost/encrypt" and "http://localhost/decrypt" endpoints. (From both Postman and curl)
- I can **encrypt** or **decrypt** successfully in the code using the TextEncryptor as well.
- Also encrypted properties in the application.properties gets **decrypted** without any issues.

However I want to use the asymmetric key as it is more secured and so I generated the asymmetric key using keytool,

```
keytool -genkeypair -alias mytestkey -keyalg RSA 
  -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" 
  -keypass changeme -keystore server.jks -storepass letmein 
  -validity 365
```
Updated the properties of bootstrap.properties

```
encrypt.key-store.location: classpath:/server.jks
encrypt.key-store.password=letmein
encrypt.key-store.alias=mytestkey
encrypt.key-store.secret=changeme
```

- I can **encrypt** or **decrypt** by making POST call to "http://localhost/encrypt" and "http://localhost/decrypt" endpoints. (From both Postman and curl)
- I can **encrypt** or **decrypt** successfully in the code using the TextEncryptor as well.

But when I add the  properties in the application.properties,

`messageinfo={cipher}AQBt2RnIRqX1UrHGfvcJpQhfurqbxjGEgeHh....
`

 I am getting the following error:

```
2018-12-03 12:03:14 - Application startup failed
java.lang.IllegalStateException: Cannot decrypt: key=messageinfo
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:202) ~[spring-cloud-context-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:166) ~[spring-cloud-context-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:96) ~[spring-cloud-context-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener$DelegatingEnvironmentDecryptApplicationInitializer.initialize(BootstrapApplicationListener.java:394) ~[spring-cloud-context-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.18.RELEASE.jar:1.5.18.RELEASE]
	at com.integration.IntegrationApplication.main(IntegrationApplication.java:20) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.18.RELEASE.jar:1.5.18.RELEASE]
Caused by: java.lang.IllegalStateException: Cannot decrypt
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:240) ~[spring-security-rsa-1.0.8.RELEASE.jar:na]
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:177) ~[spring-security-rsa-1.0.8.RELEASE.jar:na]
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:166) ~[spring-security-rsa-1.0.8.RELEASE.jar:na]
	at org.springframework.cloud.config.server.encryption.LocatorTextEncryptor.decrypt(LocatorTextEncryptor.java:52) ~[spring-cloud-config-server-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:194) ~[spring-cloud-context-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	... 14 common frames omitted
Caused by: javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383) ~[na:1.8.0_192]
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294) ~[na:1.8.0_192]
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_181]
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_181]
	at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[na:1.8.0_191]
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:228) ~[spring-security-rsa-1.0.8.RELEASE.jar:na]
	... 18 common frames omitted

```

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by adnanmian** [comment]
I have managed to find the issue, it was issue related to **Java** environment, I have multiple **Java SDK** installed on my box, My JAVA_HOME (and PATH) was pointing to **Java 11 SDK,** so when I used the **keytool** to generate key, it was using **Java 11**.

However in my Spring Studio, it was pointing to Java 8 SDK, so when I ran the project it used the Java 8 to read and decrypt. 

So After:

- Uninstalled Java 11
- Changed the JAVA_HOME (and PATH) to point to Java 8 SDK
- Regenerated key using keytool

It Started working fine.

Many thanks for your help
