### ISSUE TITLE
Could not restart when integration spring-cloud-starter-bus-amqp

### ISSUE THREAD

**Issue by koradji2046** [spring-cloud/spring-cloud-config#1255]
Could not restart when integration spring-cloud-starter-bus-amqp on spring boot 1.5.10

### POM.xml
```xml
    <artifactId>microservice-config-server</artifactId>
    <version>1.0-SNAPSHOT</version>
    <groupId>com.koradji.cloud</groupId>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bus-amqp</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
```
### application.yml
```
server.port: 8040
spring.application.name: microservice-config-server
spring.profiles.active: native

endpoints.shutdown.enabled: true
endpoints.restart.enabled: true
endpoints.shutdown.sensitive: false
endpoints.restart.sensitive: false

security.basic.enabled: false

management:
  security.enabled: false
  context-path: /admin
```
### App.java
```java
@SpringBootApplication
@EnableConfigServer
public class App {
    public static void main(String[] args) {
        SpringApplication.run(ConfigServerApplication.class,args);
    }
}
```

curl -x post localhost:8040/admin/restart

app.jar reported error:
```
2019-02-26 11:01:38.409 ERROR 7764 --- [       Thread-8] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@4b86805d has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1064) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1175) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.getOrderedBeansOfType(BootstrapApplicationListener.java:310) ~[spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.apply(BootstrapApplicationListener.java:284) ~[spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:105) ~[spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:68) ~[spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:296) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.restart(RestartEndpoint.java:167) [spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.invoke(RestartEndpoint.java:99) [spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.invoke(RestartEndpoint.java:48) [spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.actuate.endpoint.mvc.AbstractEndpointMvcAdapter.invoke(AbstractEndpointMvcAdapter.java:56) [spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:42) [spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.cloud.context.restart.RestartMvcEndpoint.access$001(RestartMvcEndpoint.java:34) [spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.cloud.context.restart.RestartMvcEndpoint$1.run(RestartMvcEndpoint.java:51) [spring-cloud-context-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

2019-02-26 11:01:38.409  INFO 7764 --- [       Thread-8] o.s.c.context.restart.RestartEndpoint    : Could not restart: org.springframework.context.annotation.AnnotationConfigApplicationContext@4b86805d has been closed already
```

**Comment by spencergibb** [comment]
Please stop opening the same issue in multiple repositories
