### ISSUE TITLE
Git config property 'basedir' not working for value 'file:///D:/PathToGit'

### ISSUE THREAD

**Issue by komoo1** [spring-cloud/spring-cloud-config#1343]
Using 'file:///' with spring.cloud.config.server.git.basedir does not get directory resolved.
Spring cloud version - Greenwich-RELEASE
Spring Boot - 2.1.2-RELEASE

### Config server application.yml
```
server:
    port: 8888
spring:
    cloud:
        config:
            server:
                accept-empty: false
                git:
                    basedir: "file:///D:/Folder/PathToConfig"
                    clone-on-start: false
                    force-pull: false
                    uri: "https://gitserver.com/scm/config.git"
                    username: "user"
                    password: "pass"
    profiles:
        active: git
```

### Error message on startup

```
Caused by: java.lang.IllegalStateException: Basedir does not exist and can not be created: file:\D:\Folder\PathToConfig
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.afterPropertiesSet(MultipleJGitEnvironmentRepository.java:104) ~[spring-cloud-config-server-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
```

However, config server is okay when 'basedir' value is changed to D:/Folder/PathToConfig

**Comment by spencergibb** [comment]
None of the team has a Windows machine to try and diagnose this.

**Comment by spencergibb** [comment]
Not sure is base dir is a resource that can accept a uri. Just a file path

**Comment by spencergibb** [comment]
`baseDir` is a `File` object, not a `Resource` that accepts uri's.
