### ISSUE TITLE
Dirty files found when refresh

### ISSUE THREAD

**Issue by mufool** [spring-cloud/spring-cloud-config#1394]
```
2019-05-23 20:27:43.360 ERROR 106431 --- [nio-8096-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultEnvironmentRepository': Invocation of init method failed; nested exception is org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown eb489ea677a11f9af758d674f4d5636e5dea7a1f] with root cause

org.eclipse.jgit.errors.MissingObjectException: Missing unknown eb489ea677a11f9af758d674f4d5636e5dea7a1f
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:148) ~[org.eclipse.jgit-3.6.1.201501031845-r.jar!/:3.6.1.201501031845-r]
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229) ~[org.eclipse.jgit-3.6.1.201501031845-r.jar!/:3.6.1.201501031845-r]
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:840) ~[org.eclipse.jgit-3.6.1.201501031845-r.jar!/:3.6.1.201501031845-r]
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753) ~[org.eclipse.jgit-3.6.1.201501031845-r.jar!/:3.6.1.201501031845-r]
        at org.eclipse.jgit.api.CloneCommand.parseCommit(CloneCommand.java:322) ~[org.eclipse.jgit-3.6.1.201501031845-r.jar!/:3.6.1.201501031845-r]
        at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:234) ~[org.eclipse.jgit-3.6.1.201501031845-r.jar!/:3.6.1.201501031845-r]
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:129) ~[org.eclipse.jgit-3.6.1.201501031845-r.jar!/:3.6.1.201501031845-r]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:433) ~[spring-cloud-config-server-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.initClonedRepository(JGitEnvironmentRepository.java:249) ~[spring-cloud-config-server-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.afterPropertiesSet(JGitEnvironmentRepository.java:181) ~[spring-cloud-config-server-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.afterPropertiesSet(MultipleJGitEnvironmentRepository.java:68) ~[spring-cloud-config-server-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1689) ~[spring-beans-4.3.22.RELEASE.jar!/:4.3.22.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1627) ~[spring-beans-4.3.22.RELEASE.jar!/:4.3.22.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:398) ~[spring-beans-4.3.22.RELEASE.jar!/:4.3.22.RELEASE]
        at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:107) ~[spring-cloud-context
...
2019-05-23 20:27:45.447  WARN 106431 --- [io-8096-exec-17] .c.s.e.MultipleJGitEnvironmentRepository : Dirty files found:
```

spring boot 1.5.10
spring cloud Edgware.RELEASE

**Comment by mufool** [comment]
Config like this.
 ````
config:
      server:
        git:
          uri: xxx
          ignoreLocalSshSettings: true
          force-pull: true
          search-paths: develop,alpha
          basedir: config/config-repo
          clone-on-start: true
          strict-host-key-checking: false
          privateKey: 
```

**Comment by spencergibb** [comment]
Edgware.RELEASE is fairly old, can you try with Edgware.SR5?

**Comment by mufool** [comment]
> Edgware.RELEASE is fairly old, can you try with Edgware.SR5?

I tried Edgware.SR5 and it is the same problem.

**Comment by spencergibb** [comment]
IIRC there is a property you can set. I'll have to look it up tomorrow

**Comment by mufool** [comment]
> IIRC there is a property you can set. I'll have to look it up tomorrow

Thanks!

**Comment by mufool** [comment]
![image](https://user-images.githubusercontent.com/11265466/58315335-f764d580-7e43-11e9-8f23-967ca7cd63d8.png)

The basedir file has not been changed, but isWorkingTreeClean returns false, and then always reports Dirty files error.Please help me to see how to solve this problem, thank you！
