### ISSUE TITLE
No HttpServletRequest available exception when using Vault with Cloud Config Server

### ISSUE THREAD

**Issue by pankesh** [spring-cloud/spring-cloud-config#1446]
Hi,

I am getting a similar error as reported in issue #1393. Moving to 2.1.3.RELEASE doesn't seem to have resolved the bug completely - or maybe i'm missing something else. Please advice. Below is the stack error stack i get.

```
Caused by: java.lang.IllegalStateException: No HttpServletRequest available
	at org.springframework.cloud.config.server.environment.HttpRequestConfigTokenProvider.getToken(HttpRequestConfigTokenProvider.java:41) ~[spring-cloud-config-server-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.VaultEnvironmentRepository.getToken(VaultEnvironmentRepository.java:218) ~[spring-cloud-config-server-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.VaultEnvironmentRepository.read(VaultEnvironmentRepository.java:209) ~[spring-cloud-config-server-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.VaultEnvironmentRepository.findOne(VaultEnvironmentRepository.java:147) ~[spring-cloud-config-server-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.CompositeEnvironmentRepository.findOne(CompositeEnvironmentRepository.java:52) ~[spring-cloud-config-server-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.EnvironmentRepositoryPropertySourceLocator.locate(EnvironmentRepositoryPropertySourceLocator.java:55) ~[spring-cloud-config-server-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) ~[spring-cloud-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:628) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:364) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
```

I've attached the sample project which replicated this error
[vault-config-server.zip](https://github.com/spring-cloud/spring-cloud-config/files/3506192/vault-config-server.zip)

thanks!

**Comment by spencergibb** [comment]
You have to provide a vault token via `spring.cloud.config.server.vault.token`

**Comment by pankesh** [comment]
Thanks Spencer! Passing the token resolved the exception. That error threw me off as it wasn't clear to me that i had to pass that as a config. I was under the impression that I would just have to pass via the request `X-Config-Token` after the application started up.

I did look at the `VaultEnvironmentProperties` class and that didn't have the token either. 

My suggestion is to add a note in the documentation around the same as there is no mention of this anywhere. If you agree I can submit a PR with that update to the docs.

tx again!

**Comment by spencergibb** [comment]
PRs welcome
