### ISSUE TITLE
Git ssh URI port number is ignored

### ISSUE THREAD

**Issue by minhster99** [spring-cloud/spring-cloud-config#1451]
Version: Greenwich.SR1

Using a URI like
git@mygit:2222/secops/secrets.git

The port is 2222 because I am hosting my own Git instance on docker and cannot use the standard 22 port as it will clash with the host ssh port.

I get the following stacktrace
```
Caused by: org.eclipse.jgit.errors.TransportException: git@mygit:2222/secops/secrets.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:192)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1271)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:243)
	... 154 common frames omitted
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:146)
	... 161 common frames omitted
```

I debugged into the code that is parsing the URI and in the org.eclipse.jgit.transport.URIish class, it is ignoring the port.
```
                matcher = RELATIVE_SCP_URI.matcher(s);
		if (matcher.matches()) {
			user = matcher.group(1);
			pass = matcher.group(2);
			host = matcher.group(3);
			rawPath = matcher.group(4);
			path = rawPath;
			return;
		}
```

Is this a bug in the jgit libraries? or expected behaviour?

**Comment by minhster99** [comment]
I forgot to say how I know it is being ignored. I got this from the Jsch logging

```
2019-08-19 15:37:50,757 [main] INFO  jsch - Connecting to mygit port 22
2019-08-19 15:37:51,045 [main] INFO  jsch - Connection established
```

It's connecting on port 22 to the host container's ssh port instead of 2222.

**Comment by ryanjbaxter** [comment]
The exception does suggest it is trying on `2222` but in any case if you believe the problem is with jgit I suggest you open an issue there.

**Comment by minhster99** [comment]
After investigating the jgit API, I've worked out the problem. The URI in the Spring Cloud Config documentation is incorrect. The documentation lists the format to be

```
git@host:port/repo1.git
```

It should instead be
```
ssh://git@host:port/repo1.git
```

So in my case, it worked once I changed it to ssh://git@mygit:2222/secops/secrets.git

I got the idea from this page
https://www.codeaffine.com/2014/12/09/jgit-authentication/

**Comment by spencergibb** [comment]
Where in the documentation is it wrong?

**Comment by minhster99** [comment]
https://cloud.spring.io/spring-cloud-config/reference/html/#_git_ssh_configuration_using_properties
