### ISSUE TITLE
Spring cloud vault starter (2020.0.2) pulling in spring vault core v 2.3.0 

### ISSUE THREAD

**Issue by hasnainjaved** [spring-cloud/spring-cloud-config#1846]
**Describe the bug**
Spring cloud version 2020.0.2 pulls in spring cloud core v 2.3.0 and the application fails to start with the following error

```
Caused by: java.lang.NoSuchMethodError: 'void org.springframework.vault.support.SslConfiguration.<init>(org.springframework.vault.support.SslConfiguration$KeyStoreConfiguration, org.springframework.vault.support.SslConfiguration$KeyStoreConfiguration, java.util.List, java.util.List)'
	at org.springframework.cloud.vault.config.VaultConfiguration.createSslConfiguration(VaultConfiguration.java:101)
	at org.springframework.cloud.vault.config.VaultConfiguration.createClientHttpRequestFactory(VaultConfiguration.java:109)
	at org.springframework.cloud.vault.config.VaultAutoConfiguration.clientHttpRequestFactoryWrapper(VaultAutoConfiguration.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
```

**Sample**
A simple [spring cloud vault](https://start.spring.io/#!type=maven-project&language=kotlin&platformVersion=2.4.4.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=cloud-starter-vault-config) project with just spring cloud vault dependency can be used to reproduce it. Running the following command will show the dependency tree. It should be pulling in spring vault core v 2.3.2

`./mvnw dependency:tree`

```
[INFO] +- org.springframework.cloud:spring-cloud-starter-vault-config:jar:3.0.2:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:3.0.2:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:3.0.2:compile
[INFO] |  |  |  \- org.springframework.security:spring-security-crypto:jar:5.4.5:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-commons:jar:3.0.2:compile
[INFO] |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.9.RELEASE:compile
[INFO] |  |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
[INFO] |  |        \- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-vault-config:jar:3.0.2:compile
[INFO] |  \- org.springframework.vault:spring-vault-core:jar:2.3.0:compile
```

**Comment by spencergibb** [comment]
Duplicates #1841
