### ISSUE TITLE
Config Server not started

### ISSUE THREAD

**Issue by hendisantika** [spring-cloud/spring-cloud-config#1892]
**Describe the bug**
I follow this doc https://docs.spring.io/spring-cloud-config/docs/3.0.3/reference/html/ to set `#spring.config.import=optional:configserver:http://localhost:8888` but Config Server not started with following error:
```
/Users/hendisantika/.sdkman/candidates/java/11.0.9.j9-adpt/bin/java -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -javaagent:/Users/hendisantika/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7142.45/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=53068:/Users/hendisantika/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7142.45/IntelliJ IDEA.app/Contents/bin -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dfile.encoding=UTF-8 -classpath /Users/hendisantika/Desktop/tes/Config Server/target/classes:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-netflix-eureka-client/3.0.2/spring-cloud-starter-netflix-eureka-client-3.0.2.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter/3.0.2/spring-cloud-starter-3.0.2.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-context/3.0.2/spring-cloud-context-3.0.2.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-commons/3.0.2/spring-cloud-commons-3.0.2.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-netflix-eureka-client/3.0.2/spring-cloud-netflix-eureka-client-3.0.2.jar:/Users/hendisantika/.m2/repository/com/netflix/eureka/eureka-client/1.10.11/eureka-client-1.10.11.jar:/Users/hendisantika/.m2/repository/com/netflix/netflix-commons/netflix-eventbus/0.3.0/netflix-eventbus-0.3.0.jar:/Users/hendisantika/.m2/repository/com/netflix/netflix-commons/netflix-infix/0.3.0/netflix-infix-0.3.0.jar:/Users/hendisantika/.m2/repository/commons-jxpath/commons-jxpath/1.3/commons-jxpath-1.3.jar:/Users/hendisantika/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar:/Users/hendisantika/.m2/repository/org/antlr/antlr-runtime/3.4/antlr-runtime-3.4.jar:/Users/hendisantika/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar:/Users/hendisantika/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/Users/hendisantika/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar:/Users/hendisantika/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar:/Users/hendisantika/.m2/repository/com/thoughtworks/xstream/xstream/1.4.14/xstream-1.4.14.jar:/Users/hendisantika/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:/Users/hendisantika/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar:/Users/hendisantika/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar:/Users/hendisantika/.m2/repository/com/netflix/servo/servo-core/0.12.21/servo-core-0.12.21.jar:/Users/hendisantika/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:/Users/hendisantika/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/Users/hendisantika/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/Users/hendisantika/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar:/Users/hendisantika/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/hendisantika/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0.jar:/Users/hendisantika/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/hendisantika/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.4/jackson-annotations-2.11.4.jar:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar:/Users/hendisantika/.m2/repository/org/codehaus/jettison/jettison/1.4.0/jettison-1.4.0.jar:/Users/hendisantika/.m2/repository/com/netflix/eureka/eureka-core/1.10.11/eureka-core-1.10.11.jar:/Users/hendisantika/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.3.0/woodstox-core-5.3.0.jar:/Users/hendisantika/.m2/repository/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-loadbalancer/3.0.2/spring-cloud-starter-loadbalancer-3.0.2.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-loadbalancer/3.0.2/spring-cloud-loadbalancer-3.0.2.jar:/Users/hendisantika/.m2/repository/io/projectreactor/reactor-core/3.4.5/reactor-core-3.4.5.jar:/Users/hendisantika/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar:/Users/hendisantika/.m2/repository/io/projectreactor/addons/reactor-extra/3.4.3/reactor-extra-3.4.3.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-cache/2.4.5/spring-boot-starter-cache-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-context-support/5.3.6/spring-context-support-5.3.6.jar:/Users/hendisantika/.m2/repository/com/stoyanr/evictor/1.0.0/evictor-1.0.0.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-config-server/3.0.3/spring-cloud-config-server-3.0.3.jar:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-config-client/3.0.3/spring-cloud-config-client-3.0.3.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-web/5.3.6/spring-web-5.3.6.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-beans/5.3.6/spring-beans-5.3.6.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.4.5/spring-boot-starter-web-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.4.5/spring-boot-starter-json-2.4.5.jar:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.11.4/jackson-datatype-jdk8-2.11.4.jar:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.11.4/jackson-module-parameter-names-2.11.4.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.4.5/spring-boot-starter-tomcat-2.4.5.jar:/Users/hendisantika/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.45/tomcat-embed-core-9.0.45.jar:/Users/hendisantika/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.45/tomcat-embed-websocket-9.0.45.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-webmvc/5.3.6/spring-webmvc-5.3.6.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-aop/5.3.6/spring-aop-5.3.6.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-expression/5.3.6/spring-expression-5.3.6.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.4.5/spring-boot-starter-validation-2.4.5.jar:/Users/hendisantika/.m2/repository/org/glassfish/jakarta.el/3.0.3/jakarta.el-3.0.3.jar:/Users/hendisantika/.m2/repository/org/hibernate/validator/hibernate-validator/6.1.7.Final/hibernate-validator-6.1.7.Final.jar:/Users/hendisantika/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar:/Users/hendisantika/.m2/repository/org/jboss/logging/jboss-logging/3.4.1.Final/jboss-logging-3.4.1.Final.jar:/Users/hendisantika/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/hendisantika/.m2/repository/org/springframework/security/spring-security-crypto/5.4.6/spring-security-crypto-5.4.6.jar:/Users/hendisantika/.m2/repository/org/springframework/security/spring-security-rsa/1.0.9.RELEASE/spring-security-rsa-1.0.9.RELEASE.jar:/Users/hendisantika/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.64/bcpkix-jdk15on-1.64.jar:/Users/hendisantika/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.64/bcprov-jdk15on-1.64.jar:/Users/hendisantika/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/5.1.3.201810200350-r/org.eclipse.jgit-5.1.3.201810200350-r.jar:/Users/hendisantika/.m2/repository/com/jcraft/jsch/0.1.55/jsch-0.1.55.jar:/Users/hendisantika/.m2/repository/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.jar:/Users/hendisantika/.m2/repository/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.jar:/Users/hendisantika/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/Users/hendisantika/.m2/repository/org/eclipse/jgit/org.eclipse.jgit.http.apache/5.1.3.201810200350-r/org.eclipse.jgit.http.apache-5.1.3.201810200350-r.jar:/Users/hendisantika/.m2/repository/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar:/Users/hendisantika/.m2/repository/org/yaml/snakeyaml/1.27/snakeyaml-1.27.jar:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.11.4/jackson-dataformat-yaml-2.11.4.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.4.5/spring-boot-starter-actuator-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter/2.4.5/spring-boot-starter-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.4.5/spring-boot-starter-logging-2.4.5.jar:/Users/hendisantika/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/hendisantika/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/hendisantika/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.13.3/log4j-to-slf4j-2.13.3.jar:/Users/hendisantika/.m2/repository/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar:/Users/hendisantika/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar:/Users/hendisantika/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.4.5/spring-boot-actuator-autoconfigure-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-actuator/2.4.5/spring-boot-actuator-2.4.5.jar:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.11.4/jackson-datatype-jsr310-2.11.4.jar:/Users/hendisantika/.m2/repository/io/micrometer/micrometer-core/1.6.6/micrometer-core-1.6.6.jar:/Users/hendisantika/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar:/Users/hendisantika/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-devtools/2.4.5/spring-boot-devtools-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot/2.4.5/spring-boot-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-context/5.3.6/spring-context-5.3.6.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.4.5/spring-boot-autoconfigure-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-configuration-processor/2.4.5/spring-boot-configuration-processor-2.4.5.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-core/5.3.6/spring-core-5.3.6.jar:/Users/hendisantika/.m2/repository/org/springframework/spring-jcl/5.3.6/spring-jcl-5.3.6.jar com.hendisantika.microservices.configserver.ConfigServerApplication
08:57:49.949 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Unable to load config data from 'optional:configserver:https://localhost:8888'
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:128)
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.resolve(StandardConfigDataLocationResolver.java:115)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.lambda$resolve$1(ConfigDataLocationResolvers.java:115)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers$$Lambda$175/000000000000000000.get(Unknown Source)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:126)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:115)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:107)
	at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:101)
	at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:93)
	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:81)
	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:121)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:230)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:97)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplicationRunListeners$$Lambda$129/000000000000000000.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:375)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at com.hendisantika.microservices.configserver.ConfigServerApplication.main(ConfigServerApplication.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalStateException: File extension is not known to any PropertySourceLoader. If the location is meant to reference a directory, it must end in '/'
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferencesForFile(StandardConfigDataLocationResolver.java:214)
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:125)
	... 37 common frames omitted

Process finished with exit code 0

```

**Sample**
Here the sample to reproduce the issue: https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration

Thanks

**Comment by ryanjbaxter** [comment]
That is not a sample but a collection of yaml files

**Comment by hendisantika** [comment]
Oh Sorry. Here's the Config Server repo sample https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/config-server

**Comment by ryanjbaxter** [comment]
Why are you trying to point a config server at another config server for its configuration?

**Comment by hendisantika** [comment]
which part?

**Comment by ryanjbaxter** [comment]
Using `spring.config.import="optional:configserver" is not valid for a config server
https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/config-server/-/blob/main/src/main/resources/application.properties#L12-13

**Comment by hendisantika** [comment]
I commented it.

**Comment by ryanjbaxter** [comment]
I know but that is what your original issue was referencing.  So if that is not the problem what is?
