### ISSUE TITLE
Asymmetric encryption for a config server running in docker - NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

### ISSUE THREAD

**Issue by techjourney010** [spring-cloud/spring-cloud-config#1920]
I want to use asymmetric encryption for my Spring Cloud Config server which runs in docker.
**Spring Boot version:** 2.4.4
**Spring Cloud Config:**

![image](https://user-images.githubusercontent.com/82444414/123434298-fda27e80-d5d4-11eb-9715-065c218f916b.png)

Symmetric encryption worked both running the app from intellij and from docker
Asymmetric encryption makes me trouble, but only when running the configserver from docker. 
Running from intellij it worked:
![image](https://user-images.githubusercontent.com/82444414/123436813-b36ecc80-d5d7-11eb-9094-0190a05049d4.png)

Running configserver in docker gives me troubles.

**Generate the jks:**
`keytool -genkeypair -alias myKeystoreSecret -keyalg RSA -dname "CN=John Doe,OU=my_unit,O=my_organization,L=Dallas,S=Texas,C=US" -validity 365 -keypass myStrongPass1 -keystore scc.jks -storepass myStrongPass1`

**Check the jks:** `keytool -list -v -keystore scc.jks`
![image](https://user-images.githubusercontent.com/82444414/123421989-3f77f880-d5c6-11eb-8aa8-2cc3922d5a94.png)
...
![image](https://user-images.githubusercontent.com/82444414/123422330-b9a87d00-d5c6-11eb-9a9f-2174d415591d.png)

**bootstrap.yml**
```
encrypt:
  key-store:
    location: ${KEYSTORE_LOCATION}
    password: ${KEYSTORE_PASSWORD}
    alias: ${KEYSTORE_ALIAS}
```
**Env. file (scc_env.txt):**
```
KEYSTORE_LOCATION=classpath:scc.jks
KEYSTORE_PASSWORD=myStrongPass1
KEYSTORE_ALIAS=myKeystoreSecret
```
**Dockerfile:**
```
FROM openjdk:11-jre-slim
WORKDIR /project
COPY ./target/*.jar ./app.jar
EXPOSE 8888
ENTRYPOINT ["java", "-jar", "/project/app.jar"]
```
I use openjdk11 so that I could also use JFR, which comes for free starting with openjdk 11.
![image](https://user-images.githubusercontent.com/82444414/123427371-35a5c380-d5cd-11eb-8347-e78f926fbd66.png)

**Compose:**
```
version: '3.1'

services:
  configserver:
    image: configserver:0.0.6
    ...
    env_file:
      - ../RESOURCES/scc_env.txt
```
**Trying to encrypt a word:**
 ```
ERROR 1 --- [nio-8888-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot load keys from store: class path resource [scc.jks]] with root cause
configserver    |
configserver    | java.io.IOException: Invalid keystore format
configserver    |       at java.base/sun.security.provider.JavaKeyStore.engineLoad(Unknown Source) ~[na:na]
configserver    |       at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source) ~[na:na]
configserver    |       at java.base/java.security.KeyStore.load(Unknown Source) ~[na:na]
configserver    |       at org.springframework.security.rsa.crypto.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:70) ~[spring-security-rsa-1.0.9.RELEASE.jar!/:na]
...
```
**I specify the "type" in the bootstrap.yml:**
 `encrypt.key-store.type: PKCS12`

Then try again to encrypt a word:
```
 ERROR 1 --- [nio-8888-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot load keys from store: class path resource [scc.jks]] with root cause
configserver    |
configserver    | java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
configserver    |       at java.base/javax.crypto.Mac.getInstance(Unknown Source) ~[na:na]
configserver    |       at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source) ~[na:na]
configserver    |       at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source) ~[na:na]
configserver    |       at java.base/java.security.KeyStore.load(Unknown Source) ~[na:na]
configserver    |       at org.springframework.security.rsa.crypto.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:70) ~[spring-security-rsa-1.0.9.RELEASE.jar!/:na]
...
```
Create another jks from inside of the container & try to access it:
![image](https://user-images.githubusercontent.com/82444414/123434004-b3210200-d5d4-11eb-9b03-7b5b305d1c3f.png)

**Comment by techjourney010** [comment]
It was the openjdk version havind issues, not SCC. For example with openjdk:16-slim it worked!
I will close the issue since it is not a SCC issue
