### ISSUE TITLE
Benign java.io.IOException from JGit on startup

### ISSUE THREAD

**Issue by seanmmills** [spring-cloud/spring-cloud-config#2028]
Upgrading our Spring Cloud Config server from Spring Cloud 2020.0.3 to 2021.0.0 caused a seemingly benign error reported in the logs when deploying to kubernetes.

```
2022-01-03 20:04:02,892 [tributeWriter-2] ERROR org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig - Cannot save config file 'FileBasedConfig[/.config/jgit/config]'
java.io.IOException: Creating directories for /.config/jgit failed
  at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:412)
  at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:138)
  at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:219)
  at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:740)
  at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$4(FS.java:426)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
```

I found this [stackoverflow](https://stackoverflow.com/questions/65731005/jgit-throws-java-io-ioexception-creating-directories-for-config-jgit-failed) describing the problem and solution.  I can add the `XDG_CONFIG_HOME` environment variable, however I think it would be great if a solution was provided in SCC.

**Comment by ryanjbaxter** [comment]
Interesting, IDK what we can do about it as it appears to be something JGit is doing.

Does everything still work despite the exception?

**Comment by mpkorstanje** [comment]
Having found myself in the same situation, it would appear that everything is working as expected.

**Comment by ryanjbaxter** [comment]
Thanks @mpkorstanje.  I will try and take a look at it, but it will be low priority since everything is working.

**Comment by mpkorstanje** [comment]
No problem!

I don't think this a problem for Spring to solve. It's up to the OS that runs the application to set `XDG_CONFIG_HOME` correctly.

In my case this variable was set correctly but the filesystem was mounted as read-only and do the user dit was not writable.

I'll file an issue with JGit to more gracefully handle read-only file systems.

**Comment by ryanjbaxter** [comment]
Could you post a comment to the JGit issue here?

**Comment by mpkorstanje** [comment]
It already exists:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=560555

**Comment by ryanjbaxter** [comment]
Thanks!

**Comment by ryanjbaxter** [comment]
We probably need to document this

**Comment by howardem** [comment]
Hi @ryanjbaxter is this issue already documented? I'm running into a similar problem after upgrading my Spring Cloud Config Server to Spring Boot 3.3.3, Spring Cloud 2023.0.3, running on Java 21 and building my OCI image with Paketo Buildpacks. 

Thanks in advance!

**Comment by ryanjbaxter** [comment]
I just added a note to the docs
