### ISSUE TITLE
Refresh through actuator throws an exception 'Error binding spring.config.import'

### ISSUE THREAD

**Issue by ruospalo** [spring-cloud/spring-cloud-config#2043]
Spring cloud config client throws an exception when try to refresh the properties loaded 
through spring.config.import=configserver:http://localhost:8080

```shell
 curl -X POST http://localhost:8888/actuator/refresh
```

```shell
java.lang.NullPointerException: Cannot invoke "org.springframework.boot.context.properties.source.ConfigurationPropertySource.getConfigurationProperty(org.springframework.boot.context.properties.source.ConfigurationPropertyName)" because "source" is null
	at org.springframework.boot.context.properties.bind.Binder.findProperty(Binder.java:444) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:390) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:340) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:259) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:246) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.getConfigImportArray(ConfigDataMissingEnvironmentPostProcessor.java:113) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.propertySourceWithConfigImport(ConfigDataMissingEnvironmentPostProcessor.java:108) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor$$Lambda$273/0x00000000e0319790.test(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.getConfigImports(ConfigDataMissingEnvironmentPostProcessor.java:98) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor.postProcessEnvironment(ConfigDataMissingEnvironmentPostProcessor.java:77) ~[spring-cloud-commons-3.0.4.jar:3.0.4]
	at org.springframework.cloud.context.refresh.ConfigDataContextRefresher.updateEnvironment(ConfigDataContextRefresher.java:92) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:101) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:94) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:41) ~[spring-cloud-context-3.0.4.jar:3.0.4]
 ```

There is a basic example here [here](https://github.com/ruospalo/sprint-cloud-config-test)
I've also tested with the latest version of spring cloud.

Thank you very much in advance

**Comment by spencergibb** [comment]
I'm unable to recreate the issue. Your ports are confusing. you have config import `configserver:http://localhost:8080` (8080 is the port of the client) and above you refresh 8888 (default port of config server).

**Comment by ruospalo** [comment]
Sorry. I've just push the server and update [README](https://github.com/ruospalo/sprint-cloud-config-test/blob/main/README.md) to recreate.

**Comment by spencergibb** [comment]
Changing to
```
    import: configserver:http://localhost:8888
```
works around the problem.
