### ISSUE TITLE
Unable to lookup messages from resource bundles

### ISSUE THREAD

**Issue by radarsh** [spring-cloud/spring-cloud-config#217]
When I configure Spring Cloud Config on my Spring Boot app, the lookup of messages using `MessageSource.getMessage` fails with the below stacktrace.

```
org.springframework.context.NoSuchMessageException: No message found under code 'my.message' for locale 'en'.
	at org.springframework.context.support.DelegatingMessageSource.getMessage(DelegatingMessageSource.java:69)
	at org.springframework.context.support.DelegatingMessageSource.getMessage(DelegatingMessageSource.java:66)
	at org.springframework.context.MessageSource$getMessage.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:138)
	at app.application.controller.ApplicationController.test(ApplicationController.groovy:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.sprinork.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:295)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:68)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocoactConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

I am using a pretty standard setup, with Spring Cloud Bus and Rabbit MQ.

I have tried by placing the `messages.properties` file both inside the application (under `src/main/resources`) and inside the config Git repo.

An interesting observation is that the implementation of `MessageSource` I get when running through Spring Cloud Config is `DelegatingMessageSource` whereas if I run as a plain Spring Boot app, it is `ResourceBundleMessageSource`.

**Comment by spencergibb** [comment]
We don't support putting resources bundles in config server yet, see #216 and I don't see any cloud classes in your stack trace.

**Comment by radarsh** [comment]
The problem is, it doesn't work even if I keep the resource bundles inside my Spring Boot application. Spring Cloud Config seems to break the default behaviour of `MessageSource`.

**Comment by spencergibb** [comment]
What version are you using? Do you have project that recreates the problem?

**Comment by radarsh** [comment]
I will try to create an example project.

Here are the dependencies of the Config Server

```
dependencies {
    compile "org.springframework.boot:spring-boot-starter"
    compile "org.codehaus.groovy:groovy-all:2.4.3"
    compile "org.springframework.cloud:spring-cloud-config-server:1.0.1.RELEASE"
    compile "org.springframework.cloud:spring-cloud-starter-bus-amqp:1.0.3.RELEASE"
    compile "org.springframework.amqp:spring-rabbit:1.4.5.RELEASE"
}
```

And those of the Spring Boot app:

```
dependencies {
    compile "org.springframework.boot:spring-boot-starter-web"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.cloud:spring-cloud-starter-config:1.0.1.RELEASE"
    compile "org.springframework.cloud:spring-cloud-starter-bus-amqp:1.0.3.RELEASE"
    compile "org.codehaus.groovy:groovy-all:2.4.3"
    compile "org.springframework.amqp:spring-rabbit:1.4.5.RELEASE"
}
```

**Comment by radarsh** [comment]
I have created a sample for you at https://github.com/radarsh/spring-cloud-config-example

**Comment by spencergibb** [comment]
@radarsh Apparently it is a problem with [spring-boot](https://github.com/spring-projects/spring-boot/issues/3803). See https://github.com/spring-cloud/spring-cloud-commons/issues/29 for a similar issue.

The following build.gradle works for me. I was unable to get 1.2.6.BUILD-SNAPSHOT to work.

```
buildscript {
    repositories {
        mavenCentral()
        maven { url 'http://repo.spring.io/snapshot' }
        maven { url 'http://repo.spring.io/milestone' }
        jcenter()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE"

        classpath "org.springframework.boot:spring-boot-gradle-plugin:1.3.0.BUILD-SNAPSHOT"
        classpath "org.springframework:springloaded:1.2.4.RELEASE"
    }
}

apply plugin: 'spring-boot'
apply plugin: 'groovy'
apply plugin: "io.spring.dependency-management"

sourceCompatibility = 1.7
targetCompatibility = 1.7

repositories {
    mavenCentral()
    maven { url 'http://repo.spring.io/snapshot' }
    maven { url 'http://repo.spring.io/milestone' }
    mavenLocal()
}
dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:1.3.0.BUILD-SNAPSHOT'
    }
}


dependencies {
    compile "org.springframework.boot:spring-boot-starter-web"
    compile("org.springframework.boot:spring-boot-starter-actuator")

    compile "org.springframework.cloud:spring-cloud-starter-config:1.1.0.BUILD-SNAPSHOT"
//    compile "org.springframework.cloud:spring-cloud-starter-bus-amqp:1.0.3.RELEASE"
    compile "org.codehaus.groovy:groovy-all:$groovyVersion"
    compile "org.springframework.amqp:spring-rabbit:1.4.5.RELEASE"
}
```

**Comment by radarsh** [comment]
Thanks @spencergibb. That works for me.
