### ISSUE TITLE
Cannot decrypt key

### ISSUE THREAD

**Issue by yamen23ali** [spring-cloud/spring-cloud-config#235]
I followed exactly the same steps in here ( http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_security) however i can't seems to get it to work , i keep getting this exception :

Cannot decrypt key: (property name )  (class java.lang.IllegalStateException: Cannot decrypt)

I generated the key store and the encrypted value as the example above and my ( JCE ) java files are replaced and working fine , any ideas what might cause this ? or how can i have more info about the cause of this problem ?

============================================================
After more in depth debugging it turned out the exception originally is generated from ( Data must not be longer than 256 bytes ) which is really weird since i'm encrypting only 2 or 3 letters , the full stack for the exception is :

```
java.lang.IllegalStateException: Cannot decrypt
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:239)
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:176)
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:165)
	at org.zlounge.phoenix.configserver.TestClass.test(TestClass.java:67)
	at org.zlounge.phoenix.configserver.TestClass$$FastClassBySpringCGLIB$$cd6802c0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at org.zlounge.phoenix.configserver.TestClass$$EnhancerBySpringCGLIB$$c1f521bf.test(<generated>)
	at org.zlounge.phoenix.configserver.RunScheduler.run(RunScheduler.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.crypto.IllegalBlockSizeException: Data must not be longer than 256 bytes
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:344)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:227)
```

**Comment by dsyer** [comment]
Obviously it works fine for me (otherwise tests would be failing). Can you provide a simple project that reproduces the error? Preferably just using the `RsaSecretEncryptor`.

**Comment by dsyer** [comment]
My guess is this is a duplicate of #202 (which was an encoding issue). See also #246.
