### ISSUE TITLE
Unable to fetch config file from cloud config when use docker compose

### ISSUE THREAD

**Issue by BorisSpring** [spring-cloud/spring-cloud-config#2355]
Hello guys im haveing problem with fetchign property source form cloud config, affter it fails i try to click on link and it work perfely fine  in browser, also when i run localy it works fine, im using Spring Cloud Netflix cleint 4.0.3 And Server 4.0.4 

This is my compose.yml file 

-----------------------------------------------------------
version: '3.8'
services:
   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
     ports:
       - "9288:9288"
   jms:
     container_name: jms
     image: vromero/activemq-artemis
     ports:
       - "8161:8161"
       - "61616:61616"
   zipkin:
     container_name: zipkin
     image: openzipkin/zipkin
     ports:
       - "9411:9411"
   eureka:
     container_name: eureka
     image: sfgbeerworks/mscc-eureka-server
     ports:
      - "8761:8761"
   config:
     container_name: config
     image: sfgbeerworks/mscc-cloud-config
     ports:
      - "8888:8888"
     depends_on:
        - eureka
     environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://username:password@eureka:8761/eureka/
       EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
   inventory:
      container_name: inventory
      image: sfgbeerworks/mscc-beer-inventory-service:latest
      ports:
        - "9501:9501"
      depends_on:
        - jms
        - eureka
        - config
      environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://username:password@eureka:8761/eureka/
       EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
       SPRING_ARTEMIS_HOST: jms
       SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beer_inventory_2?useUnicode=true&characterEncoding=UTF-8
       SPRING_PROFILES_ACTIVE: local-discovery,local
       SPRING_CONFIG_IMPORT: optional:configserver:http://config:8888
       SPRING_CLOUD_CONFIG_URI: http://config:8888
       SPRING_CLOUD_CONFIG_PROFILE: local
       SPRING_APPLICATION_NAME: inventory
#      restart: on-failure
   beer:
     container_name: beer
     image: sfgbeerworks/mscc-beer-service:latest
     ports:
       - "9500:9500"
     depends_on:
       - jms
       - eureka
       - config
       - inventory
     environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://username:password@eureka:8761/eureka/
       EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
       SPRING_ARTEMIS_HOST: jms
       SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beer_service_2?useUnicode=true&characterEncoding=UTF-8
       SPRING_PROFILES_ACTIVE: local-discovery,local
       SFG_BEER_INVENTORY_SERVICE: http://inventory:9501
       SFG_BEER_ORDER_SERVICE: http://order:9502
       SPRING_CONFIG_IMPORT: optional:configserver:http://config:8888
       SPRING_CLOUD_CONFIG_URI: http://config:8888
       SPRING_CLOUD_CONFIG_PROFILE: local
       SPRING_APPLICATION_NAME: beer-service
#     restart: on-failure
   order:
     container_name: order
     image: sfgbeerworks/mscc-beer-order-service
     ports:
       - "9502:9502"
     depends_on:
       - jms
       - eureka
       - config
       - beer
     environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://username:password@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_PROFILES_ACTIVE: local-discovery,local
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beer_order_service_2?useUnicode=true&characterEncoding=UTF-8
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer:9500
      SPRING_CONFIG_IMPORT: optional:configserver:http://config:8888
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_CLOUD_CONFIG_PROFILE: local
      SPRING_APPLICATION_NAME: order
#     restart: on-failure
   gateway:
      image: sfgbeerworks/mscc-gateway
      ports:
        - "9090:9090"
      depends_on:
        - eureka
        - config
        - inventory
        - beer
        - order
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://username:password@eureka:8761/eureka/
        
        ****This is how i created images 
---------------------------------------****
        
        FROM openjdk:19 as builder
WORKDIR application
ADD maven/${project.build.finalName}.jar ${project.build.finalName}.jar
RUN java -Djarmode=layertools -jar ${project.build.finalName}.jar extract

FROM openjdk:19
LABEL PROJECT_NAME=${project.artifactId} \
       PROJECT=${project.id}

EXPOSE 9500
WORKDIR application

COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "org.springframework.boot.loader.JarLauncher"]

--------------------- Exception im issuing 

2023-11-19T00:04:20.161755083Z 00:04:20.157 [main] ERROR org.springframework.boot.SpringApplication -- Application run failed
2023-11-19T00:04:20.161810783Z org.springframework.cloud.config.client.ConfigClientFailFastException: Could not locate PropertySource and the fail fast property is set, failing
2023-11-19T00:04:20.161818883Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.doLoad(ConfigServerConfigDataLoader.java:201)
2023-11-19T00:04:20.161824283Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:102)
2023-11-19T00:04:20.161829383Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:61)
2023-11-19T00:04:20.161834183Z 	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:96)
2023-11-19T00:04:20.161839383Z 	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
2023-11-19T00:04:20.161844083Z 	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
2023-11-19T00:04:20.161849182Z 	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:115)
2023-11-19T00:04:20.161854782Z 	at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
2023-11-19T00:04:20.161860182Z 	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:229)
2023-11-19T00:04:20.161865082Z 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
2023-11-19T00:04:20.161870182Z 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
2023-11-19T00:04:20.161875082Z 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
2023-11-19T00:04:20.161880082Z 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
2023-11-19T00:04:20.161884682Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
2023-11-19T00:04:20.161891282Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
2023-11-19T00:04:20.161896782Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
2023-11-19T00:04:20.161901782Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
2023-11-19T00:04:20.161906482Z 	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
2023-11-19T00:04:20.161911182Z 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
2023-11-19T00:04:20.161924282Z 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
2023-11-19T00:04:20.161929682Z 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
2023-11-19T00:04:20.161934282Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
2023-11-19T00:04:20.161939582Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
2023-11-19T00:04:20.161944481Z 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
2023-11-19T00:04:20.161949681Z 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:360)
2023-11-19T00:04:20.161954581Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
2023-11-19T00:04:20.161959381Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
2023-11-19T00:04:20.161963881Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
2023-11-19T00:04:20.161968581Z 	at com.main.MsccBeerServiceApplication.main(MsccBeerServiceApplication.java:12)
2023-11-19T00:04:20.161973481Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
2023-11-19T00:04:20.161978181Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
2023-11-19T00:04:20.161983481Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2023-11-19T00:04:20.161988481Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
2023-11-19T00:04:20.161993081Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2023-11-19T00:04:20.161997781Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2023-11-19T00:04:20.162003081Z Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8888/beer-service/local": Connection refused
2023-11-19T00:04:20.162008381Z 	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888)
2023-11-19T00:04:20.162013481Z 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868)
2023-11-19T00:04:20.162018181Z 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764)
2023-11-19T00:04:20.162023481Z 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:646)
2023-11-19T00:04:20.162028281Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.getRemoteEnvironment(ConfigServerConfigDataLoader.java:306)
2023-11-19T00:04:20.162033381Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.doLoad(ConfigServerConfigDataLoader.java:119)
2023-11-19T00:04:20.162038081Z 	... 34 common frames omitted
2023-11-19T00:04:20.162047280Z Caused by: java.net.ConnectException: Connection refused
2023-11-19T00:04:20.162052480Z 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
2023-11-19T00:04:20.162057180Z 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
2023-11-19T00:04:20.162083980Z 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:535)
2023-11-19T00:04:20.162090180Z 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
2023-11-19T00:04:20.162099280Z 	at java.base/java.net.Socket.connect(Socket.java:666)
2023-11-19T00:04:20.162107680Z 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
2023-11-19T00:04:20.162111480Z 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
2023-11-19T00:04:20.162119080Z 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
2023-11-19T00:04:20.162122280Z 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:279)
2023-11-19T00:04:20.162125380Z 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:384)
2023-11-19T00:04:20.162128580Z 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:406)
2023-11-19T00:04:20.162132180Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1308)
2023-11-19T00:04:20.162135980Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
2023-11-19T00:04:20.162146079Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
2023-11-19T00:04:20.162154279Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1056)
2023-11-19T00:04:20.162160479Z 	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:75)
2023-11-19T00:04:20.162165279Z 	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
2023-11-19T00:04:20.162170379Z 	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
2023-11-19T00:04:20.162175279Z 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862)
2023-11-19T00:04:20.162180279Z 	... 38 common frames omitted
2023-11-19T00:05:31.603824046Z 00:05:31.600 [main] ERROR org.springframework.boot.SpringApplication -- Application run failed
2023-11-19T00:05:31.603904145Z org.springframework.cloud.config.client.ConfigClientFailFastException: Could not locate PropertySource and the fail fast property is set, failing
2023-11-19T00:05:31.603929445Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.doLoad(ConfigServerConfigDataLoader.java:201)
2023-11-19T00:05:31.603934145Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:102)
2023-11-19T00:05:31.603938045Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:61)
2023-11-19T00:05:31.603952645Z 	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:96)
2023-11-19T00:05:31.603956645Z 	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
2023-11-19T00:05:31.603960545Z 	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
2023-11-19T00:05:31.603964245Z 	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:115)
2023-11-19T00:05:31.603967845Z 	at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
2023-11-19T00:05:31.603971545Z 	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:229)
2023-11-19T00:05:31.603975145Z 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
2023-11-19T00:05:31.603978845Z 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
2023-11-19T00:05:31.603982545Z 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
2023-11-19T00:05:31.603986245Z 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
2023-11-19T00:05:31.603989844Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
2023-11-19T00:05:31.603995244Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
2023-11-19T00:05:31.603998944Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
2023-11-19T00:05:31.604002644Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
2023-11-19T00:05:31.604006344Z 	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
2023-11-19T00:05:31.604009944Z 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
2023-11-19T00:05:31.604013444Z 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
2023-11-19T00:05:31.604017144Z 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
2023-11-19T00:05:31.604020744Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
2023-11-19T00:05:31.604055444Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
2023-11-19T00:05:31.604059644Z 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
2023-11-19T00:05:31.604069244Z 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:360)
2023-11-19T00:05:31.604073344Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
2023-11-19T00:05:31.604077844Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
2023-11-19T00:05:31.604081543Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
2023-11-19T00:05:31.604085043Z 	at com.main.MsccBeerServiceApplication.main(MsccBeerServiceApplication.java:12)
2023-11-19T00:05:31.604099343Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
2023-11-19T00:05:31.604102943Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
2023-11-19T00:05:31.604106443Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2023-11-19T00:05:31.604110043Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
2023-11-19T00:05:31.604113543Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2023-11-19T00:05:31.604117043Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2023-11-19T00:05:31.604121343Z Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8888/beer-service/local": Connection refused
2023-11-19T00:05:31.604125343Z 	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888)
2023-11-19T00:05:31.604139843Z 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868)
2023-11-19T00:05:31.604143443Z 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764)
2023-11-19T00:05:31.604147543Z 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:646)
2023-11-19T00:05:31.604151343Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.getRemoteEnvironment(ConfigServerConfigDataLoader.java:306)
2023-11-19T00:05:31.604155243Z 	at org.springframework.cloud.config.client.ConfigServerConfigDataLoader.doLoad(ConfigServerConfigDataLoader.java:119)
2023-11-19T00:05:31.604159143Z 	... 34 common frames omitted
2023-11-19T00:05:31.604162743Z Caused by: java.net.ConnectException: Connection refused
2023-11-19T00:05:31.604166443Z 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
2023-11-19T00:05:31.604170143Z 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
2023-11-19T00:05:31.604173743Z 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:535)
2023-11-19T00:05:31.604177342Z 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
2023-11-19T00:05:31.604181042Z 	at java.base/java.net.Socket.connect(Socket.java:666)
2023-11-19T00:05:31.604188342Z 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
2023-11-19T00:05:31.604192042Z 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
2023-11-19T00:05:31.604195742Z 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
2023-11-19T00:05:31.604199342Z 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:279)
2023-11-19T00:05:31.604203242Z 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:384)
2023-11-19T00:05:31.604206842Z 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:406)
2023-11-19T00:05:31.604210442Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1308)
2023-11-19T00:05:31.604214242Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
2023-11-19T00:05:31.604217942Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
2023-11-19T00:05:31.604221542Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1056)
2023-11-19T00:05:31.604225942Z 	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:75)
2023-11-19T00:05:31.604229842Z 	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
2023-11-19T00:05:31.604233742Z 	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
2023-11-19T00:05:31.604237542Z 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862)
2023-11-19T00:05:31.604241142Z 	... 38 common frames omitted
 i read previous question on stackoverflow and github, google, youtube, but nothing can help me to figure out what is going on and how to solve this ..

**Comment by BorisSpring** [comment]
Yes ill post my project when i come back to home, i didnt seen notification

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
