### ISSUE TITLE
spring-cloud-config-monitor error polling local repo

### ISSUE THREAD

**Issue by sergiorc** [spring-cloud/spring-cloud-config#239]
Hi
I'm trying 1.1.0.BUILD-SNAPSHOT version of spring-cloud-config-monitor (I've not found any release candidate) to monitor  pushes in a remote github.

I'm NOT using a local file:// repository, but FileMonitorConfiguration is scheduled to monitor changes in 
a local repository. 
The watcher service has not initialized since there is no local repo.

```
java.lang.NullPointerException
	at org.springframework.cloud.config.monitor.FileMonitorConfiguration.filesFromEvents(FileMonitorConfiguration.java:208)
	at org.springframework.cloud.config.monitor.FileMonitorConfiguration.poll(FileMonitorConfiguration.java:171)
```

**Comment by sergiorc** [comment]
Last snapshot works without problems.
Thanks a lot
