### ISSUE TITLE
Config Service loses connection with local git repository

### ISSUE THREAD

**Issue by pfournea** [spring-cloud/spring-cloud-config#356]
Spring Cloud Config Service (v 1.1.0.M4) loses connection with the cloned git repository (config service connects with ssh to a remote git repo). We had this error several times. It doesn't occur very often but once every few weeks we have following error:

```
_ERROR - Servlet.service() for servlet [dispatcherServlet] in context with path [/genservices/configservice] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot load environment] with root cause [o.a.j.l.DirectJDKLog:log:182]
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: D:\sxData\java_io_tmpdir\configservice\config-repo-3209480337859690098
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:575) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
	at org.eclipse.jgit.api.Git.open(Git.java:113) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
	at org.eclipse.jgit.api.Git.open(Git.java:97) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository$JGitFactory.getGitByOpen(JGitEnvironmentRepository.java:353) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.openGitRepository(JGitEnvironmentRepository.java:260) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:237) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:146) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:121) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:108) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:40) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:137) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.EnvironmentEncryptorEnvironmentRepository.findOne(EnvironmentEncryptorEnvironmentRepository.java:53) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.EnvironmentController.labelled(EnvironmentController.java:97) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.EnvironmentController.defaultLabel(EnvironmentController.java:86) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
ERROR - Servlet.service() for servlet [dispatcherServlet] in context with path [/genservices/configservice] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot load environment] with root cause [o.a.j.l.DirectJDKLog:log:182]
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: D:\sxData\java_io_tmpdir\configservice\config-repo-3209480337859690098
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:575) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
	at org.eclipse.jgit.api.Git.open(Git.java:113) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
	at org.eclipse.jgit.api.Git.open(Git.java:97) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository$JGitFactory.getGitByOpen(JGitEnvironmentRepository.java:353) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.openGitRepository(JGitEnvironmentRepository.java:260) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:237) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:146) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:121) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:108) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:40) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:137) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.EnvironmentEncryptorEnvironmentRepository.findOne(EnvironmentEncryptorEnvironmentRepository.java:53) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.EnvironmentController.labelled(EnvironmentController.java:97) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.cloud.config.server.environment.EnvironmentController.defaultLabel(EnvironmentController.java:86) ~[spring-cloud-config-server-1.1.0.M4.jar!/:1.1.0.M4]_
```

The location of the git repo (`D:\sxData\java_io_tmpdir\configservice\config-repo-3209480337859690098`) is still present on the server!

Any ideas?

Thx!

Regards,

Peter F

**Comment by dsyer** [comment]
Any more detailed steps to reproduce? I never saw this and I've had a config server running since 2014.

**Comment by spencergibb** [comment]
My guess is it has something to do with windows `D:\sxData`. Your's is on linux.

**Comment by pfournea** [comment]
Thanks for the feedback. The service is indeed running an a windows 2008 Server. For the moment I can't give more details ..I try to find a way to reproduce the problem. By that I hope I can give more details.

Regards,

Peter

**Comment by dsyer** [comment]
Is "D:" a network drive, or a local hard disk?

**Comment by pfournea** [comment]
it's a network drive. Windows is running as a ESX host (VMware)

**Comment by dsyer** [comment]
My guess is it's more to do with the fact that it's a network drive. You should expect that drives can become unavailable for short periods, and (unless I'm missing something), this isn't preventing the Config Server from working once the drive comes back again. Is there anything we can do here, really?
