### ISSUE TITLE
Escaped brackets are not handled when seralizing to json or yaml

### ISSUE THREAD

**Issue by gmagniez** [spring-cloud/spring-cloud-config#360]
I have an input json configuration file (I don't manage it) converted to yaml which contains brackets in the key string (something that looks like css selector).
i.e : 

```
abcd:
  '[class="xyz"]': "a string"
```

If I ask config server for properties it works.
`abcd.[class="xyz"]: a string`
But when I try to get json or yaml I get a 400 Bad request with a NumberFormatException:

```
java.lang.NumberFormatException: For input string: "[class="xyz""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.valueOf(Integer.java:766)
    at org.springframework.cloud.config.server.environment.EnvironmentController.addArrays(EnvironmentController.java:291)
    at org.springframework.cloud.config.server.environment.EnvironmentController.convertToMap(EnvironmentController.java:213)
    at org.springframework.cloud.config.server.environment.EnvironmentController.labelledJsonProperties(EnvironmentController.java:150)
    at org.springframework.cloud.config.server.environment.EnvironmentController.jsonProperties(EnvironmentController.java:139)
```

I still have the error even when escaping the brackets.

**Comment by dsyer** [comment]
I'm not sure I even want to fix that. If you need the raw YAML you can get it via the file path.
