### ISSUE TITLE
Actuator version problem with latest version of Spring Boot

### ISSUE THREAD

**Issue by colin-shine** [spring-cloud/spring-cloud-config#379]
Sample project that reproduces the error is here:
https://github.com/colin-shine/cloud-config-actuator-issue 

An empty Spring Boot project (version `1.4.0.M2`) with the following dependencies fails to start.
`spring-boot-starter-actuator:1.4.0.M2`
`spring-cloud-starter-config:1.1.0.RC2`

```
2016-04-21 14:26:40.885 ERROR 147568 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.actuate.endpoint.InfoEndpoint.invoke()Ljava/util/Map;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:841) ~[spring-context-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1182) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1171) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at issues.spring.shine.colin.Application.main(Application.java:11) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_72]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.actuate.endpoint.InfoEndpoint.invoke()Ljava/util/Map;
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration.infoEndpoint(RefreshEndpointAutoConfiguration.java:170) ~[spring-cloud-context-1.1.0.RC3.jar:1.1.0.RC3]
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration.postProcessAfterInitialization(RefreshEndpointAutoConfiguration.java:158) ~[spring-cloud-context-1.1.0.RC3.jar:1.1.0.RC3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	... 19 common frames omitted
```

**Comment by spencergibb** [comment]
Duplicates #372
