### ISSUE TITLE
Config Server with SVN unable to read JSON/Text Files

### ISSUE THREAD

**Issue by Zenithonnet** [spring-cloud/spring-cloud-config#404]
With Brixton.BUILD-SNAPSHOT/Brixton.RELEASE dependency version, am able to read yml files from SVN(configured via ConfigServer) but am not able to read any other text/JSON files hosted in it.

When trying to access 
http://localhost:8888/application/default/master/Policy.json am getting the below exception. Please let me know if the feature is yet to be added or any other dependency version needs to be added to enable it.

```
ERROR --- [nio-8888-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
    at org.springframework.cloud.config.server.resource.ResourceController.resolve(ResourceController.java:69) ~[spring-cloud-config-server-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.re
```

**Comment by spencergibb** [comment]
Are you sure you have the latest snapshot? Line 69 in master that has deployed snapshots is a blank line and so is the RELEASE. https://github.com/spring-cloud/spring-cloud-config/blob/v1.1.0.RELEASE/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java#L69

**Comment by Zenithonnet** [comment]
Updated the pom.xml with latest pom.xml and added SVN dependency. NOam am getting this exception. Is SVN not compatabile with latest configs?

**Exception**
2016-05-19 10:38:03.041  INFO 14936 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CONFIGSERVER1/WSUSOH30347CLWW.nam.nsroot.net:configserver1:8888 - registration status: 204
2016-05-19 10:38:05.233 ERROR 14936 --- [nio-8888-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.cloud.config.server.environment.NoSuchLabelException: No label found for: master] with root cause

org.springframework.cloud.config.server.environment.NoSuchLabelException: No label found for: master
	at org.springframework.cloud.config.server.environment.SvnKitEnvironmentRepository.getPaths(SvnKitEnvironmentRepository.java:108) ~[spring-cloud-config-server-1.1.1.BUILD-SNAPSHOT.jar:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.config.server.environment.SvnKitEnvironmentRepository.getLocations(SvnKitEnvironmentRepository.java:86) ~[spring-cloud-config-server-1.1.1.BUILD-SNAPSHOT.jar:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:40) ~[spring-cloud-config-server-1.1.1.BUILD-SNAPSHOT.jar:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.config.server.environment.EnvironmentEncryptorEnvironmentRepository.findOne(EnvironmentEncryptorEnvironmentRepository.java:53) ~[spring-cloud-config-server-1.1.1.BUILD-SNAPSHOT.jar:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.config.server.resource.ResourceController.resolve(ResourceController.java:93) ~[spring-cloud-config-server-1.1.1.BUILD-SNAPSHOT.jar:1.1.1.BUILD-SNAPSHOT]

**pom.xml**
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.ccp.server</groupId>
	<artifactId>ccp-server</artifactId>
	<version>${pro.version}</version>
	<packaging>jar</packaging>
	<name>Config Server</name>
	<description>Config Server demo project</description>

	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Brixton.BUILD-SNAPSHOT</version>
		<relativePath /> 
	</parent>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.tmatesoft.svnkit</groupId>
			<artifactId>svnkit</artifactId>
		</dependency>
	</dependencies>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<start-class>demo.ConfigServerApplication</start-class>
		<java.version>1.7</java.version>
		<docker.image.prefix>springcloud</docker.image.prefix>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>http://repo.spring.io/libs-snapshot-local</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>http://repo.spring.io/libs-milestone-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>http://repo.spring.io/libs-release-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>http://repo.spring.io/libs-snapshot-local</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>http://repo.spring.io/libs-milestone-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
</project>

**Comment by dsyer** [comment]
SVN doesn't normally have a "master". Did you mean to ask for "trunk"?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
