### ISSUE TITLE
@RefreshScope doesn't work on bean annotated with @Configuration

### ISSUE THREAD

**Issue by shakuzen** [spring-cloud/spring-cloud-config#43]
I am not sure the root cause is Spring Cloud Config, but since the `@RefreshScope` and refresh functionality is part of Spring Cloud Config, I thought I would start here. And perhaps this is expected behavior, but it was a surprise to me.

I basically followed the Spring Cloud Config tutorial [here](http://qiita.com/making@github/items/704d8e254e03c5cce546) but was including the `@Configuration` annotation via the new `@SpringBootApplication` annotation. I was able to reproduce the issue by only adding a `@Configuration` annotation to the client's ClientApp class of the tutorial. GitHub for the tutorial is available [here](https://github.com/making/config).

**Working Client**

``` java
@EnableAutoConfiguration
@ComponentScan
@RestController
@RefreshScope
public class ClientApp {
    @Value("${bar:World!}")
    String bar;

    @RequestMapping("/")
    String hello() {
        return "Hello " + bar + "!";
    }

    public static void main(String[] args) {
        SpringApplication.run(ClientApp.class, args);
    }
}
```

**Not working client**

``` java
@Configuration // **This is the only thing different!**
@EnableAutoConfiguration
@ComponentScan
@RestController
@RefreshScope
public class ClientApp {
    @Value("${bar:World!}")
    String bar;

    @RequestMapping("/")
    String hello() {
        return "Hello " + bar + "!";
    }

    public static void main(String[] args) {
        SpringApplication.run(ClientApp.class, args);
    }
}
```

**Error**
The following error is thrown after trying to access http://localhost:8080 following a refresh.

```
2014-11-25 00:03:56.487 ERROR 9868 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.clientApp': Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: demo.ClientApp.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V] with root cause

java.lang.NoSuchMethodError: demo.ClientApp.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
    at demo.ClientApp$$EnhancerBySpringCGLIB$$9e153ad7.setBeanFactory(<generated>)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor$EnhancedConfigurationBeanPostProcessor.postProcessPropertyValues(ConfigurationClassPostProcessor.java:448)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
    at org.springframework.beans.factory.support.AbstractBeanFactory$2.getObject(AbstractBeanFactory.java:341)
    at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:447)
    at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:181)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:336)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.getTarget(CglibAopProxy.java:676)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:627)
    at demo.ClientApp$$EnhancerBySpringCGLIB$$316d9b47.hello(<generated>)
...
```

**Question**
Is this expected behavior? This also happens with Spring Boot 1.2.0.RC2's new `@SpringBootApplication` annotation that includes the `@Configuration` annotation, which is how I originally ran into this issue. I suppose there is no need to annotate this class with the `@Configuration` annotation since it is not actually configuring anything, but that is often a default annotation that people put on their main Application class, as I believe is evidenced by the creation of the `@SpringBootApplication` annotation. I also suppose in an app with more substance, the Controller and/or beans containing `@Value` annotations would likely be separated out from the main class. Still, perhaps this is something to make more clear or fix.

**Comment by luohaoGit** [comment]
nice
