### ISSUE TITLE
Encrypt/Decrypt works in server endpoint; but doesn't in Spring Cloud Config Client

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud/spring-cloud-config#453]
Setup
====
* The sever is configured with `spring.cloud.config.server.encrypt.enabled=false`, expecting all clients to have the `.jks` file (as described at `http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_creating_a_key_store_for_testing`.

* Values are checked in the command-line

Encrypt command-line
-----

* Original value: `PW0N28rfQJmGRjtPJGxmaxxhRt8FkjHm8YMZiHIp`

```
$ curl localhost:8888/encrypt -d PW0N28rfQJmGRjtPJGxmaxxhRt8FkjHm8YMZiHIp
AQBFZ4PAj2dmTDjdlx6DWSuGlSuxLn6kbpFbz2JiREVnxfiuvFeKNBIR9TFtmpcNMlp2i9W104HMH
RVVnV3BXx2XoDgwi0EMf/mXTL0a/dLMsoym3L585VDyq0UYcM5YTGghTO5WH/5l3hKrtH7zyvq
wYD/gdLf/KHTBX3BFCcXH3Aro3apKaMJRk+8EMuDaYyebGX/Yz+BPvt8hRNqupQZUyfCdEJsKK
U2DwiOkd64nP0ZtZT3LsPfi5HcAGWxSpy5UIvsx6LrjYKtc+gzfvTldrIdpx+NipGkutEUxAdi+46CzZ
bsTth2ytHyDAwHrGtbZmxe8VnW0xzSXHlMeX+kXVcFGYvCyPr/cGFlnHdNwip9xVDwfJfgcZ1FYN
iDwV2Jy4knmjeL+LaEWa1zGxS8DFxKJrX0xidFHCuw50ArZ8Q==
```

URL Encoded value
-----

I started getting the error `Data must not be longer than 256 bytes` on the server while trying to decrypt the value without URL encoding it. So, According to https://github.com/spring-cloud/spring-cloud-config/issues/202#issuecomment-125338215 and https://github.com/spring-cloud/spring-cloud-config/issues/246#issuecomment-145919088, we should URL encode the value.

```
AQCxQ5aTOadoh2UA1pV0ksLN3bZOmpbabs8BTXEbskQyxfOZWS6znKFSEx6aDadtdMDBlmRKA
4pW%2FTeF1GylJRHsn1FAygdVXFHYMg5gGtER94zL28eIwfQTCE9jHCSSn2nXVm6m9lqtHtqAmP
T%2FFNNOK7vd%2BkMLRyFqUfTdQ3szHtaT9STIhV2zQLkOV5lhKRJu6ea3wdDfv3%2BX%2FrrXY
2ydCN0Pvfwyx2gwAozG151UH4hRtzLcXfeCRGziOrV9UiJWq%2FYVRMUUDZ92QFqetvK91%2B6
1FTlk%2BBsCiIE0HX6FxLasbPati0DPiOaHvrgswo9Tyu4Po7xWhtrN2g4VUpYNSESvAqtia7ljTWkzd
3HAWXMNYjDlQlY8Q4sG8p%2B%2B7HgJJzh9FpFoAAD42rQIGcWCe%2BfKj2Vq2DZ7IJjx2T8nLg
%3D%3D
```

Decrypt command-line
--- 
```
$ curl localhost:8888/decrypt -d AQCxQ5aTOadoh2UA1pV0ksLN3bZOmpbabs8BTXEbskQyxfOZWS6znKFSEx6aDadtdMDBlmRKA
4pW%2FTeF1GylJRHsn1FAygdVXFHYMg5gGtER94zL28eIwfQTCE9jHCSSn2nXVm6m9lqtHtqAmP
T%2FFNNOK7vd%2BkMLRyFqUfTdQ3szHtaT9STIhV2zQLkOV5lhKRJu6ea3wdDfv3%2BX%2FrrXY
2ydCN0Pvfwyx2gwAozG151UH4hRtzLcXfeCRGziOrV9UiJWq%2FYVRMUUDZ92QFqetvK91%2B6
1FTlk%2BBsCiIE0HX6FxLasbPati0DPiOaHvrgswo9Tyu4Po7xWhtrN2g4VUpYNSESvAqtia7ljTWkzd
3HAWXMNYjDlQlY8Q4sG8p%2B%2B7HgJJzh9FpFoAAD42rQIGcWCe%2BfKj2Vq2DZ7IJjx2T8nLg
%3D%3D
PW0N28rfQJmGRjtPJGxmaxxhRt8FkjHm8YMZiHIp
```

So, in theory, all the steps are covered well, and I can use the server to `encrypt/decrypt` values. However, I'm getting into problems while replicating this scenario from a Spring Cloud Config client application.

Spring Cloud Config Client
=====

* Client has the `.jks` from the server to be able to decrypt the keys
* Client can successfully decrypt other values that are shorter
* While decrypting longer keys, the client fails with `Cannot decrypt` error

```
2016-07-26 15:02:37.739 ERROR 6266 --- [  restartedMain] o.s.boot.SpringApplication               :
 Application startup failed
java.lang.IllegalStateException: Cannot decrypt: key=onboard.apps[0].awsSecretKey
```

I placed the URL-encoded value of the cipher text in the property. Here's the output of the server with the secret:

```json
$ curl localhost:8888/publisher-default.json | jq
{
  "onboard": {
    "apps": [
      {
        "awsAccessKey": "{cipher}AQCrSdRit6wg+MdL4JQUjk4/3JkmxeF1JTpELVBruaDaIiis4cqvxBReU50wlrU8SdSXJA+CS9Xn9GBiCtfecICSQKhBrypjQ+orQ17wIwOn/YSLtZZ0/VoFS7IDfTXBxUVZz+IJizGAiR8Wdxf5Wrk8LCYyOljNeyl48/CQMYUcy+rmvLloKsESZwNw7Fq0Qu3CvEaoM++mj3TW7z6WcOIBL5UgVCzQ6OnauqD7274jljJStliSYWiC9JUjxYTsWcYhVwQxyA1Kt+15vKJsZjec69/r94vD7ejHYzLFHx30XIwt9kNoEfOdJ3repplYeRxlFA4INhXDsNb0Bd2QYhEzzbwYWQ9dcMrJPg+3nhbQpcpsauHqRfgiiUgpWqklqkPjRvrNmLK8zMuJQECrhA5e",
        "awsS3Bucket": "caas-87542TESTTESTTESest",
        "awsSecretKey": "{cipher}AQCxQ5aTOadoh2UA1pV0ksLN3bZOmpbabs8BTXEbskQyxfOZWS6znKFSEx6aDadtdMDBlmRKA4pW%2FTeF1GylJRHsn1FAygdVXFHYMg5gGtER94zL28eIwfQTCE9jHCSSn2nXVm6m9lqtHtqAmPT%2FFNNOK7vd%2BkMLRyFqUfTdQ3szHtaT9STIhV2zQLkOV5lhKRJu6ea3wdDfv3%2BX%2FrrXY2ydCN0Pvfwyx2gwAozG151UH4hRtzLcXfeCRGziOrV9UiJWq%2FYVRMUUDZ92QFqetvK91%2B61FTlk%2BBsCiIE0HX6FxLasbPati0DPiOaHvrgswo9Tyu4Po7xWhtrN2g4VUpYNSESvAqtia7ljTWkzd3HAWXMNYjDlQlY8Q4sG8p%2B%2B7HgJJzh9FpFoAAD42rQIGcWCe%2BfKj2Vq2DZ7IJjx2T8nLg%3D%3D",
        "githubAccessToken": "2122890f8f8da966dfdf532e586c8c857eec0fb4",
        "githubOrgRepo": "servicesplatform-tools/spring-cloud-config-publisher-config",
        "githubWebhookSecret": "secret"
      },
      {
        "awsAccessKey": "{cipher}AQAQMIjB/qktDoUT3lNvr6oMBWvKCD86QY4twtOG1dSCkThYzyDFwWEsivSMCo4XjolkcDm7JStnmPT+sxg9H0tIgDNAg37DReWpoBx8va/chWpNEKKFFbPTsJ4YkIXsldpV3kIhmE2CjtH1Wpr0NA4em3Nr9htSaJSpC+eIICLsVPRKatnbmKHzctoH9/azbrglkOEJIsAGAMjn99q6zWyb0Qghg7UdUniw+WyjS3b6MmW6G/HERtFm+H8yl2oA5ojz85+wlROhlUdHtzzN1v4srQLy4FAS7Lt92KNE+VbS7VVN55dCYoFkLi8KqfpbLLejRsxC+5SL4GMhkDF8qUAsTTYE95cRmBdKl+7ASyHPv9xNgAOyLLqEtE/DIhIQPPrhqWzQ8O1/HNEOTZt8sw1a",
        "awsS3Bucket": "ttrc-TESTTESTTEST-us-west-2",
        "awsSecretKey": "{cipher}AQCxQ5aTOadoh2UA1pV0ksLN3bZOmpbabs8BTXEbskQyxfOZWS6znKFSEx6aDadtdMDBlmRKA4pW%2FTeF1GylJRHsn1FAygdVXFHYMg5gGtER94zL28eIwfQTCE9jHCSSn2nXVm6m9lqtHtqAmPT%2FFNNOK7vd%2BkMLRyFqUfTdQ3szHtaT9STIhV2zQLkOV5lhKRJu6ea3wdDfv3%2BX%2FrrXY2ydCN0Pvfwyx2gwAozG151UH4hRtzLcXfeCRGziOrV9UiJWq%2FYVRMUUDZ92QFqetvK91%2B61FTlk%2BBsCiIE0HX6FxLasbPati0DPiOaHvrgswo9Tyu4Po7xWhtrN2g4VUpYNSESvAqtia7ljTWkzd3HAWXMNYjDlQlY8Q4sG8p%2B%2B7HgJJzh9FpFoAAD42rQIGcWCe%2BfKj2Vq2DZ7IJjx2T8nLg%3D%3D",
        "githubAccessToken": "2122890f8f8da966dfdf532e586c8c857eec0fb4",
        "githubOrgRepo": "servicesplatform-tools/ctg-confg",
        "githubWebhookSecret": "secret"
      }
    ]
  }
}
```

Questions
=====

* Should I place the Encoded value?
* What's wrong with this setup?

Here's the full stacktrace

```
2016-07-26 15:02:37.009  INFO 6266 --- [  restartedMain] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2016-07-26 15:02:37.547  INFO 6266 --- [  restartedMain] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=publisher, profiles=[default], label=master, version=f44d991b0e005b79b6b24012be8e8ff0c12b4017
2016-07-26 15:02:37.548  INFO 6266 --- [  restartedMain] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name='https://github.company.com/servicesplatform-tools/spring-cloud-config-publisher-config/publisher.properties'], MapPropertySource [name='https://github.company.com/servicesplatform-tools/spring-cloud-config-publisher-config/publisher.yml']]]
2016-07-26 15:02:37.729  WARN 6266 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7b319855: startup date [Wed Dec 31 16:00:00 PST 1969]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@6cdc165)
2016-07-26 15:02:37.739 ERROR 6266 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Cannot decrypt: key=onboard.apps[0].awsSecretKey
        at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:195) ~[spring-cloud-context-1.1.1.RELEASE.jar:1.1.1.RELEASE]
        at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:164) ~[spring-cloud-context-1.1.1.RELEASE.jar:1.1.1.RELEASE]
        at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:94) ~[spring-cloud-context-1.1.1.RELEASE.jar:1.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633) [spring-boot-1.4.0.RC1.jar:1.4.0.RC1]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:347) [spring-boot-1.4.0.RC1.jar:1.4.0.RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-1.4.0.RC1.jar:1.4.0.RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.4.0.RC1.jar:1.4.0.RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.4.0.RC1.jar:1.4.0.RC1]
        at com.company.platform.config.publisher.PublisherApplication.main(PublisherApplication.java:13) [main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.4.0.RC1.jar:1.4.0.RC1]
Caused by: org.springframework.security.crypto.codec.InvalidBase64CharacterException: Bad Base64 input character decimal 37 in array position 76
        at org.springframework.security.crypto.codec.Base64.decode(Base64.java:629) ~[spring-security-crypto-4.1.0.RELEASE.jar:4.1.0.RELEASE]
        at org.springframework.security.crypto.codec.Base64.decode(Base64.java:253) ~[spring-security-crypto-4.1.0.RELEASE.jar:4.1.0.RELEASE]
        at org.springframework.security.rsa.crypto.RsaSecretEncryptor.decrypt(RsaSecretEncryptor.java:165) ~[spring-security-rsa-1.0.1.RELEASE.jar:na]
        at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:187) ~[spring-cloud-context-1.1.1.RELEASE.jar:1.1.1.RELEASE]
        ... 13 common frames omitted


BUILD SUCCESSFUL

Total time: 11.533 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html
```

Removing the value makes all work
=====

* Removing the longer {cipher} values from the configuration makes it to work.

```json
$ curl localhost:8888/publisher-default.json | jq
{
  "onboard": {
    "apps": [
      {
        "awsAccessKey": "{cipher}AQCrSdRit6wg+MdL4JQUjk4/3JkmxeF1JTpELVBruaDaIiis4cqvxBReU50wlrU8SdSXJA+CS9Xn9GBiCtfecICSQKhBrypjQ+orQ17wIwOn/YSLtZZ0/VoFS7IDfTXBxUVZz+IJizGAiR8Wdxf5Wrk8LCYyOljNeyl48/CQMYUcy+rmvLloKsESZwNw7Fq0Qu3CvEaoM++mj3TW7z6WcOIBL5UgVCzQ6OnauqD7274jljJStliSYWiC9JUjxYTsWcYhVwQxyA1Kt+15vKJsZjec69/r94vD7ejHYzLFHx30XIwt9kNoEfOdJ3repplYeRxlFA4INhXDsNb0Bd2QYhEzzbwYWQ9dcMrJPg+3nhbQpcpsauHqRfgiiUgpWqklqkPjRvrNmLK8zMuJQECrhA5e",
        "awsS3Bucket": "caas-87542TESTTESTTESest",
        "awsSecretKey": "PW0N28rfQJmGRjtPJGxmaxxhRt8FkjHm8YMZiHIp",
        "githubAccessToken": "2122890f8f8da966dfdf532e586c8c857eec0fb4",
        "githubOrgRepo": "servicesplatform-tools/spring-cloud-config-publisher-config",
        "githubWebhookSecret": "secret"
      },
      {
        "awsAccessKey": "{cipher}AQAQMIjB/qktDoUT3lNvr6oMBWvKCD86QY4twtOG1dSCkThYzyDFwWEsivSMCo4XjolkcDm7JStnmPT+sxg9H0tIgDNAg37DReWpoBx8va/chWpNEKKFFbPTsJ4YkIXsldpV3kIhmE2CjtH1Wpr0NA4em3Nr9htSaJSpC+eIICLsVPRKatnbmKHzctoH9/azbrglkOEJIsAGAMjn99q6zWyb0Qghg7UdUniw+WyjS3b6MmW6G/HERtFm+H8yl2oA5ojz85+wlROhlUdHtzzN1v4srQLy4FAS7Lt92KNE+VbS7VVN55dCYoFkLi8KqfpbLLejRsxC+5SL4GMhkDF8qUAsTTYE95cRmBdKl+7ASyHPv9xNgAOyLLqEtE/DIhIQPPrhqWzQ8O1/HNEOTZt8sw1a",
        "awsS3Bucket": "caas-875424724849-us-west-2",
        "awsSecretKey": "PW0N28rfQJmGRjtPJGxmaxxhRt8FkjHm8YMZiHIp",
        "githubAccessToken": "2122890f8f8da966dfdf532e586c8c857eec0fb4",
        "githubOrgRepo": "servicesplatform-tools/ctg-confg",
        "githubWebhookSecret": "secret"
      }
    ]
  }
}
```

Server logs without {cipher}
-----

```
2016-07-26 15:23:34.995  INFO 6596 --- [  restartedMain] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2016-07-26 15:23:35.591  INFO 6596 --- [  restartedMain] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=publisher, profiles=[default], label=master, version=f44d991b0e005b79b6b24012be8e8ff0c12b4017
2016-07-26 15:23:35.591  INFO 6596 --- [  restartedMain] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name='https://github.company.com/servicesplatform-tools/spring-cloud-config-publisher-config/publisher.properties'], MapPropertySource [name='https://github.company.com/servicesplatform-tools/spring-cloud-config-publisher-config/publisher.yml']]]
2016-07-26 15:23:35.882  INFO 6596 --- [  restartedMain] c.i.p.c.publisher.PublisherApplication   : No active profile set, falling back to default profiles: default
2016-07-26 15:23:35.904  INFO 6596 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7b319855: startup date [Tue Jul 26 15:23:35 PDT 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@6cdc165
2016-07-26 15:23:36.473  WARN 6596 --- [  restartedMain] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'refreshScope' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2016-07-26 15:23:36.587  INFO 6596 --- [  restartedMain] o.s.cloud.context.scope.GenericScope     : BeanFactory id=ef24ff68-9921-36dd-9356-7fbce35a8737
2016-07-26 15:23:36.604  INFO 6596 --- [  restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-07-26 15:23:36.615  INFO 6596 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$79507584] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-07-26 15:23:36.962  INFO 6596 --- [  restartedMain] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2016-07-26 15:23:36.980  INFO 6596 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service Tomcat
2016-07-26 15:23:36.981  INFO 6596 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.3
2016-07-26 15:23:37.060  INFO 6596 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2016-07-26 15:23:37.060  INFO 6596 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1156 ms
2016-07-26 15:23:37.130  INFO 6596 --- [ost-startStop-1] c.i.p.s.h.a.HealthCheckAutoConfig        : postConstruct: dirToWatch=./conf/_health offlineFilename=set-offline
2016-07-26 15:23:37.183  INFO 6596 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'healthcheck-servlet' to [/health/*]
2016-07-26 15:23:37.185  INFO 6596 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2016-07-26 15:23:37.187  INFO 6596 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-07-26 15:23:37.187  INFO 6596 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-07-26 15:23:37.187  INFO 6596 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-07-26 15:23:37.188  INFO 6596 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2016-07-26 15:23:37.275  INFO 6596 --- [  restartedMain] c.i.p.c.p.onboard.OnboardService         : Onboarded Applications: 2
2016-07-26 15:23:37.275  INFO 6596 --- [  restartedMain] c.i.p.c.p.onboard.OnboardService         : {servicesplatform-tools/ctg-confg=[accessKey=COOL*****ELLO, secretKey=PW0N*****iHIp, s3Bucket=caas*****st-2, githubToken=2122*****0fb4], servicesplatform-tools/spring-cloud-config-publisher-config=[accessKey=AKIA*****AGIA, secretKey=PW0N*****iHIp, s3Bucket=caas*****Sest, githubToken=2122*****0fb4]}
```

**Comment by marcellodesales** [comment]
For whatever reason, I tested today and I realized that this was working... Not sure if was because I had added the security library in the JRE folder and did not restart my development box... Anyway, this is working and **`without URL encoding the cipher value`**.
