### ISSUE TITLE
Brixton Config Client fails on startup if propertySources is empty

### ISSUE THREAD

**Issue by jonekdahl** [spring-cloud/spring-cloud-config#488]
When upgrading one of our applications from Angel.SR6 to Brixton.SR5 we found that the Brixton config client does not handle an empty propertySources. This was never a problem with Angel so it seems to be a regression.

This is the exception that occurs on startup:

```
2016-08-24 16:37:26.529 DEBUG 14040 --- [           main] o.s.web.client.RestTemplate              : GET request for "https://server.example.com:9040/cache/development" resulted in 200 (OK)
2016-08-24 16:37:26.530 DEBUG 14040 --- [           main] o.s.web.client.RestTemplate              : Reading [class org.springframework.cloud.config.environment.Environment] as "application/xml;charset=UTF-8" using [org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter@a33b4e3]
2016-08-24 16:37:26.564  INFO 14040 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=cache, profiles=[development], label=master, version=ffc05f008dee3dcb76eae54649c241ea101a2680
2016-08-24 16:37:26.564 ERROR 14040 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:110) ~[spring-cloud-config-client-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89) ~[spring-cloud-context-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:640) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:343) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.5.RELEASE.jar: 	1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at se.pensionsmyndigheten.microservices.cacheserver.Application.main(Application.java:34) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:88) ~[spring-cloud-config-client-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	... 12 common frames omitted
```

We use a Git repository to store our configuration so a workaround was to add a `cache.properties` file to our config repository with a dummy property in it:

```properties
# Dummy property required for Brixton config client
foo=bar
```

**Comment by ryanjbaxter** [comment]
If you don't set `spring.cloud.config.failFast=true` wouldnt that keep the same behavior you were accustomed to with Angel?

**Comment by spencergibb** [comment]
@jonekdahl I'm unable to replicate a NPE. I always have an empty list. Can you provide sample projects and git repo that replicates the problem.

What version is config server?

What does the json look like from config server (ie `/cache/development`)?

**Comment by jonekdahl** [comment]
@ryanjbaxter Probably, although we do want to fail fast if the config server is not available on startup so that is not really an option (and we already have another workaround in place).

**Comment by jonekdahl** [comment]
@spencergibb The config server version is 1.1.2.RELEASE. The response from the config server looks like this without a cache.properties file:

```xml
<Environment>
	<name>cache</name>
	<profiles>
		<profiles>development</profiles>
	</profiles>
	<label>master</label>
	<version>45c33bffd1d8245d465893cdc369b6262794268a</version>
	<propertySources/>
</Environment>
```

When I add the dummy property it looks like this:

```xml
<Environment>
	<name>cache</name>
	<profiles>
		<profiles>development</profiles>
	</profiles>
	<label>master</label>
	<version>45c33bffd1d8245d465893cdc369b6262794268a</version>
	<propertySources>
		<propertySources>
			<name>ssh://jonekd@stash.ppm.nu:7999/ew/service-config.git/cache.properties</name>
			<source>
				<foo>bar</foo>
			</source>
		</propertySources>
	</propertySources>
</Environment>
```

I'll try to extract a minimal test case but that will probably take a little time. Thanks for the swift feedback so far.

**Comment by jonekdahl** [comment]
When trying to create a minimal test case, I noticed a difference in how the configuration is fetched from the config server. They seem to be using different Accept headers.

Our non-working application:
```
DEBUG o.s.web.client.RestTemplate              : Setting request Accept header to [application/xml, text/xml, application/json, application/*+xml, application/*+json]
DEBUG o.s.web.client.RestTemplate              : GET request for "https://pml12610.ppm.nu:9040/cache/development" resulted in 200 (OK)
DEBUG o.s.web.client.RestTemplate              : Reading [class org.springframework.cloud.config.environment.Environment] as "application/xml;charset=UTF-8" using [org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter@3292d91a]
```

The working test application:
```
DEBUG o.s.web.client.RestTemplate              : Setting request Accept header to [application/json, application/*+json]
DEBUG o.s.web.client.RestTemplate              : GET request for "http://localhost:8888/client/default" resulted in 200 (OK)
DEBUG o.s.web.client.RestTemplate              : Reading [class org.springframework.cloud.config.environment.Environment] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@291fa009]
```

I haven't figured out why this happens, but the RestTemplate used to fetch the configuration in our application is configured to prefer XML over JSON. Could this be the cause of the NPE?

**Comment by spencergibb** [comment]
Yeah, I noticed that when you sent the output. It's normally json, but some xml libraries when included as dependencies auto-configure xml support. It's very likely that when it's xml the `propertySources` attr is null rather than an empty list.
