### ISSUE TITLE
update jackson dependency's version

### ISSUE THREAD

**Issue by dragontree101** [spring-cloud/spring-cloud-config#491]
my project has lots of dependency
some jar both use jackson, and spring-cloud-config's jackson version is 2.6.0+,  and other jar's jackson version update to 2.8.0+, if i use jackson is 2.6.0+, some method not in 2.8.0+, and if i use 2.8.0+, spring-cloud-config could not startup, and exception is 
```
java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.SerializationConfig
at com.fasterxml.jackson.databind.ObjectMapper.&lt;init&gt;(ObjectMapper.java:543)
at com.fasterxml.jackson.databind.ObjectMapper.&lt;init&gt;(ObjectMapper.java:460)
at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:553)
at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.&lt;init&gt;(MappingJackson2HttpMessageConverter.java:57)
at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.&lt;init&gt;(AllEncompassingFormHttpMessageConverter.java:61)
at org.springframework.web.client.RestTemplate.&lt;init&gt;(RestTemplate.java:158)
at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getSecureRestTemplate(ConfigServicePropertySourceLocator.java:151)
at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:69)
at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89)
at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:634)
at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:342)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
at com.ricebook.rhllor.first.example.Application.main(Application.java:48)
```
does spring-cloud-config can update jackson to newest 2.8.0+ verison?  
thanks!

**Comment by dragontree101** [comment]
i update spring-boot to 1.4.0 and everything is ok
