### ISSUE TITLE
Broken Test: JGitEnvironmentRepositoryTests

### ISSUE THREAD

**Issue by mwibmer** [spring-cloud/spring-cloud-config#54]
JGitEnvironmentRepositoryTests failing;

```
root cause: org.eclipse.jgit.api.errors.JGitInternalException: Object c4bd92016dc14b9fe376d9c3f7af1c9d22d44ee4 is corrupt: bad stream

java.lang.IllegalStateException: Cannot load environment
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.findOne(JGitEnvironmentRepository.java:161)
	at org.springframework.cloud.config.server.JGitEnvironmentRepositoryTests.nested(JGitEnvironmentRepositoryTests.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Object c4bd92016dc14b9fe376d9c3f7af1c9d22d44ee4 is corrupt: bad stream
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:294)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.checkout(JGitEnvironmentRepository.java:208)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.loadEnvironment(JGitEnvironmentRepository.java:179)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.findOne(JGitEnvironmentRepository.java:155)
	... 25 more
Caused by: org.eclipse.jgit.errors.CorruptObjectException: Object c4bd92016dc14b9fe376d9c3f7af1c9d22d44ee4 is corrupt: bad stream
	at org.eclipse.jgit.storage.file.UnpackedObject.open(UnpackedObject.java:189)
	at org.eclipse.jgit.storage.file.ObjectDirectory.openObject2(ObjectDirectory.java:537)
	at org.eclipse.jgit.storage.file.FileObjectDatabase.openObjectImpl2(FileObjectDatabase.java:198)
	at org.eclipse.jgit.storage.file.FileObjectDatabase.openObject(FileObjectDatabase.java:163)
	at org.eclipse.jgit.storage.file.WindowCursor.open(WindowCursor.java:123)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:817)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:730)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:229)
	... 28 more
```

**Comment by mwibmer** [comment]
Environment: 
   Windows 7 64 bit, Eclipse STS 3.6.2.RELEASE, Java 8
   Checked out MASTER https://github.com/spring-cloud/spring-cloud-config.git

Further to JGitEnvironmentRepositoryIntegrationTests.vanilla() 
fails in DirCacheCheckout.doCheckout() 
throw new CheckoutConflictException(conflicts.toArray(new String[conflicts.size()]));
ArrayList<String> conflicts contains [application.yml]

Upgraded JGit dep to latest but got the same result 
		<dependency>
			<groupId>org.eclipse.jgit</groupId>
			<artifactId>org.eclipse.jgit</artifactId>
			<version>3.6.0.201412230720-r</version>
		</dependency>

Looks like a temp file is created ok
   C:\Temp\config-repo-4175866226101475102
the temp file is deleted when the test completes

**Comment by dsyer** [comment]
I think this is fixed?

**Comment by iver3on** [comment]
I have same question.console: Cannot clone or checkout repository] with root ca use

connect timed out
what's wrong?

**Comment by dsyer** [comment]
That's not the same error is it? Can you open a new ticket, please and include a bit more detail (platform and sets to repeat).
