### ISSUE TITLE
Decrypting properties in bootstrap.yml

### ISSUE THREAD

**Issue by thirunar** [spring-cloud/spring-cloud-config#547]
I have enabled security in the cloud config server. The clients will provide the user name and password of config server for connecting to the server. I have added the config's in bootstarp.yml in the clients. Following are properties:

> spring.application.name=application_name
> spring.cloud.config.uri=http://config_server_url
> spring.cloud.config.label=some_label
> spring.cloud.config.enabled=true
> spring.cloud.config.username=admin
> spring.cloud.config.password=password

With the above configuration, the client is able to fetch the properties from the config server. Now, I want encrypt the password of the config server. I tried adding the encrypted value of the password (encrypted using cloud config /encrypt endpoint).

> spring.application.name=application_name
> spring.cloud.config.uri=http://config_server_url
> spring.cloud.config.label=some_label
> spring.cloud.config.enabled=true
> spring.cloud.config.username=admin
> spring.cloud.config.password={cipher}b8a168b7b48477a3c36b27392cfa48f587665a8adc74c12c9daf0e56f4bfb4ed

I added the 'spring-security-rsa' dependency. But still, I'm getting issue with decrypting the password. Following is the stack trace:

> `java.lang.IllegalStateException: Cannot decrypt: key=security.user.password
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:195)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:164)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.initialize(EnvironmentDecryptApplicationInitializer.java:94)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener$DelegatingEnvironmentDecryptApplicationInitializer.initialize(BootstrapApplicationListener.java:335)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:640)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
	at com.comviva.mfs.sfm.SfmApplication.main(SfmApplication.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.UnsupportedOperationException: No decryption for FailsafeTextEncryptor. Did you configure the keystore correctly?
	at org.springframework.cloud.bootstrap.encrypt.EncryptionBootstrapConfiguration$FailsafeTextEncryptor.decrypt(EncryptionBootstrapConfiguration.java:152)
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:187)
	... 14 common frames omitted`

**Comment by ryanjbaxter** [comment]
I have not seen encrypted values in `bootstrap.yml` before they are usually placed in `application.yml`.  

Also the exception mentions the key `security.user.password` but from your properties you are encrypting `spring.cloud.config.password`.
