### ISSUE TITLE
Allow support for handling InvalidPropertyException errors?

### ISSUE THREAD

**Issue by mmoayyed** [spring-cloud/spring-cloud-config#592]
Intentional attempts to bind a value to a badly-formatted property name cause exceptions of the following nature:

```
Caused by: org.springframework.beans.InvalidPropertyException: Invalid property 'serviceRegistry.initFromJson[0]' of bean class [org.apereo.cas.configuration.CasConfigurationProperties]: Property referenced in indexed property path 'initFromJson[0]' is neither an array nor a List nor a Map; returned value was [false]
     at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:406) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
      at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:280) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
      at org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanWrapper.setPropertyValue(RelaxedDataBinder.java:699) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
      at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
      at org.springframework.validation.DataBinder.applyPropertyValues(DataBinder.java:834) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.validation.DataBinder.doBind(DataBinder.java:730) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
     at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:128) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
   at org.springframework.validation.DataBinder.bind(DataBinder.java:715) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
       at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:285) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
       at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:256) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
```

The property in question `serviceRegistry.initFromJson[0]` most certainly is not a list. After researching the docs and such, I have not been able to find a way to handle and trap `InvalidPropertyException` errors that are thrown under the above condition. The fully story is that if such properties are changed across application releases and the changes (moving from String to List)  are not backward compatible, it would be good to explicitly notify the application deployer in the logs in a way that does not result in a whole exception stack, and perhaps in certain cases the application may be able to massage the value and the property name at fault to WARN the user and transform it into a value that makes sense for the current version.

This is experienced with the `1.2.1.RELEASE` release of the spring-cloud-config at this time.

**Comment by dima767** [comment]
May be this issue could be moved to Spring Boot project as it relates to the core Boot concept `RelaxedDataBinder`?

**Comment by ryanjbaxter** [comment]
@dima767 I agree
