### ISSUE TITLE
Colon in profile name yields obscure IllegalArgumentException

### ISSUE THREAD

**Issue by anders-holmberg-baath** [spring-cloud/spring-cloud-config#637]
Since around Spring Boot 1.4.0 and later in combination with Spring Cloud (at least Camden, as well as Dalston snapshots), using `:` (colon) in profile names results in a rather unhelpful error message, given:
```
GET /application/test:abc HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.43.0
Accept: */*
```
the response is:
```json
{
  "timestamp": 1487056216666,
  "status": 400,
  "error": "Bad Request",
  "exception": "java.lang.IllegalArgumentException",
  "message": "name",
  "path": "/application/test:abc"
}
```
by contrast requesting the `test_abc` profile instead works as expected.

An abbreviated stack trace yields the source of `IllegalArgumentException` as:

```
java.lang.IllegalArgumentException: name
        at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:658) ~[na:1.8.0_111]
        at sun.misc.URLClassPath.findResource(URLClassPath.java:188) ~[na:1.8.0_111]
        at java.net.URLClassLoader$2.run(URLClassLoader.java:569) ~[na:1.8.0_111]
        at java.net.URLClassLoader$2.run(URLClassLoader.java:567) ~[na:1.8.0_111]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_111]
        at java.net.URLClassLoader.findResource(URLClassLoader.java:566) ~[na:1.8.0_111]
        at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:58) ~[config-server-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at java.lang.ClassLoader.getResource(ClassLoader.java:1096) ~[na:1.8.0_111]
        at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:996) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.core.io.ClassPathResource.resolveURL(ClassPathResource.java:147) ~[spring-core-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
        at org.springframework.core.io.ClassPathResource.exists(ClassPathResource.java:135) ~[spring-core-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:469) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:444) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:380) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:215) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:184) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:171) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
```
Which points to a part of `URLClassPath` where a `MalformedURLException` is caught on constructing a `URL`, the exception is handled by the following rather unhelpful line:
```
throw new IllegalArgumentException("name");
```
which explains the exception as presented in the error message above.

Using `:` in profile names works fine with Spring Boot 1.3.8.RELEASE or earlier (only tested with Brixton).

To complicate matters, it seems the issue only occurs when running the jar with `java -jar <jarfile>`, when for instance running with the Maven plugin, `mvn spring-boot:run` the issue does not occur.

I'm pretty sure the issue is due to a change in the spring-boot project and I suspect the following commit may have something to do with the issue [Use a conventional delegation model in LaunchedURLClassLoader](https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7), but I'm not sure to which project I should add the bug report, so I'll start here.

Project demonstrating the issue: https://github.com/anders-holmberg-baath/spring-cloud-config-issue-637

**Comment by spencergibb** [comment]
I would say spring-boot. Nothing in your report leads me to think it has anything to do with spring cloud.

**Comment by anders-holmberg-baath** [comment]
Indeed. I never got around to updating an application using a profile with a colon in the name, but actually, simply running an application with `spring.profiles.active=test:abc` yields the same exception.
