### ISSUE TITLE
Config Service RepositoryNotFoundException after several days

### ISSUE THREAD

**Issue by bplies-IAS** [spring-cloud/spring-cloud-config#639]
Using 1.2.2.RELEASE running on a Linux OS and pulling a Github repo.  The implementation appears to locally cache things in `/tmp` and works just fine for about 7 days.  Then all of a sudden:

```
2017-02-14 10:56:13.743 ERROR 28890 --- [nio-8888-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot load environment] with root cause

org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /tmp/config-repo-3749076159075229979
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:575) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
        at org.eclipse.jgit.api.Git.open(Git.java:113) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
        at org.eclipse.jgit.api.Git.open(Git.java:97) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository$JGitFactory.getGitByOpen(JGitEnvironmentRepository.java:476) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.openGitRepository(JGitEnvironmentRepository.java:369) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:346) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:165) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:144) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:116) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:40) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:154) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.EnvironmentEncryptorEnvironmentRepository.findOne(EnvironmentEncryptorEnvironmentRepository.java:53) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.config.server.environment.EnvironmentController.labelled(EnvironmentController.java:112) ~[spring-cloud-config-server-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
```

The path (such as `/tmp/config-repo-3749076159075229979` in this case) will in fact exist and be about 7 days old.  Restarting creates a new /tmp entry and resolves the issue.... for a few days.

Unlike https://github.com/spring-cloud/spring-cloud-config/issues/356 this is not on Windows and is not a networked filesystem (local XFS).

I do notice that the error is in the jgit component and that is set to `3.5.3.201412180710-r` whereas `4.6.0.201612231935-r` is the latest.  I haven't yet had a chance to try a newer version out.

The symptoms remind me of a sort of "Open File Handle Resource Leak" like if all these `org.eclipse.jgit.lib.BaseRepositoryBuilder.build` calls aren't cleaning up after themselves.  I couldn't easily find any info on existing/resolved bugs in JGit for this, but maybe this has been fixed long ago.

**Comment by spencergibb** [comment]
See #640

**Comment by spencergibb** [comment]
There are issues on centos (or other linux distros) cleaning out /tmp on a regular basis. Could this be related?

**Comment by bplies-IAS** [comment]
It is CentOS so I suppose it could be related.  However while these Exceptions are being logged I can see that the path exists (but I haven't examined the actual contents - so maybe that is the real reason).  Examining the current contents of `/tmp` all non-root owned items are last_modified within the past 7 days.  

Given that these `/tmp/config-repo-*` directories are not owned by root, and there aren't any that exist from past weeks, leads me to believe that they are being cleaned up by something.

If this is the culprit, what's the preferred strategy to resolve it?  Can the Config Server detect that its local stash is missing and just make a new one (just like it does on a fresh start?).  Though perhaps not fault of the Config Server, it could improve the resilience.

**Comment by spencergibb** [comment]
@bplies-IAS see a424690962b050bf20e9e1d6239571854c894108

**Comment by bplies-IAS** [comment]
Wonderful. thanks for all the help.  I will close this issue.  The only 2 gems to extract are the jgit version bump and a possible enhancement to automatically recover from `/tmp` purges.
