### ISSUE TITLE
Config Server fails to start when basedir parent doesn't exist

### ISSUE THREAD

**Issue by georgeharley** [spring-cloud/spring-cloud-config#700]
Here is the JSON configuration

```
{
  "git": {
    "uri": "https://github.com/georgeharley/{application}-config”,
    "label": "branch1",
    "skipSslValidation": true,
    "searchPaths": "path1"
  }
}
```  

Below is a snippet taken from the backing application log...

```
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 2017-05-18 11:51:58.574 ERROR 14 --- [           main] o.s.boot.SpringApplication               : Application startup failed
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultEnvironmentRepository' defined in class path resource [org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration$GitRepositoryConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Cannot write parent of basedir (please configure a writable location): /home/vcap/app/config-repo/default
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at io.pivotal.springcloud.config.ConfigServerApplication.main(ConfigServerApplication.java:10) [classes/:na]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT Caused by: java.lang.IllegalStateException: Cannot write parent of basedir (please configure a writable location): /home/vcap/app/config-repo/default
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.afterPropertiesSet(MultipleJGitEnvironmentRepository.java:98) ~[spring-cloud-config-server-1.3.1.BUILD-SNAPSHOT.jar!/:1.3.1.BUILD-SNAPSHOT]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
2017-05-18T12:51:58.57+0100 [APP/PROC/WEB/0]OUT 	... 24 common frames omitted

``` 

The value of `basedir` is set by the SCS code before passing the configuration parameters to the Spring Cloud Config code. 

The problem does not occur when the git `uri` in the configuration JSON has no placeholder. The following JSON works fine...

```
{
  "git": {
    "uri": "https://github.com/georgeharley/config1",
    "label": "branch1",
    "cloneOnStart": true,
    "skipSslValidation": true,
    "searchPaths": "path1"
  }
}
```

**Comment by spencergibb** [comment]
In the second case `cloneOnStart=true` creates the directories and doesn't trigger the error condition.

**Comment by spencergibb** [comment]
Since you can't clone on start with placeholders with a `basedir=/home/vcap/app/config-repo/default` and `config-repo` doesn't exist will trigger the error.

**Comment by spencergibb** [comment]
@dsyer if you wanted to go in a different direction, that's ok with me.
