### ISSUE TITLE
Auto refreshing of config on client stops to work with @EnableWebSocketMessageBroker

### ISSUE THREAD

**Issue by lhwong** [spring-cloud/spring-cloud-config#707]
Auto refreshing of config on client stops to work after enabling websocket by adding the following class

```
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig extends AbstractWebSocketMessageBrokerConfigurer {
	
    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry.addEndpoint("/ws").withSockJS();
    }

    @Override
    public void configureMessageBroker(MessageBrokerRegistry config) {
        config.setApplicationDestinationPrefixes("/app");
    	config.enableStompBrokerRelay("/topic/");
    }
}

```

The following are the exception thrown upon receiving spring cloud bus message from config server
```
2017-05-28 11:42:04.593 DEBUG 26956 --- [pool-2-thread-4] o.s.a.r.listener.BlockingQueueConsumer   : Storing delivery for Consumer@7d018c58: tags=[{amq.ctag-iDfCsEiP-9ghHnMxjrSd1w=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg}], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@127.0.0.1:5672/,1), conn: Proxy@3ed3e66d Shared Rabbit Connection: SimpleConnection@23974cac [delegate=amqp://guest@127.0.0.1:5672/, localPort= 57387], acknowledgeMode=AUTO local queue size=0
2017-05-28 11:42:04.604 DEBUG 26956 --- [RyggHsJiu82Dg-1] o.s.a.r.listener.BlockingQueueConsumer   : Received message: (Body:'{"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}' MessageProperties [headers={contentType=text/plain, originalContentType=application/json;charset=UTF-8}, timestamp=null, messageId=null, userId=null, receivedUserId=null, appId=null, clusterId=null, type=null, correlationId=null, correlationIdString=null, replyTo=null, contentType=text/plain, contentEncoding=null, contentLength=0, deliveryMode=null, receivedDeliveryMode=PERSISTENT, expiration=null, priority=0, redelivered=false, receivedExchange=springCloudBus, receivedRoutingKey=springCloudBus, receivedDelay=null, deliveryTag=1, messageCount=0, consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg])
2017-05-28 11:42:04.611 DEBUG 26956 --- [RyggHsJiu82Dg-1] actMessageChannelBinder$ReceivingHandler : org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler@699c51ec received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=fb264ce0-29cb-90f7-a4cf-ac4775930909, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=text/plain, originalContentType=application/json;charset=UTF-8, timestamp=1495942924611}]
2017-05-28 11:42:04.613 DEBUG 26956 --- [RyggHsJiu82Dg-1] .DispatchingStreamListenerMessageHandler : org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler@75e9086b received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=eb9eea5a-627b-87cc-3ef8-c89ccf487a6c, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=application/json;charset=UTF-8, timestamp=1495942924612}]
2017-05-28 11:42:04.613 DEBUG 26956 --- [RyggHsJiu82Dg-1] o.s.c.s.b.StreamListenerMessageHandler   : org.springframework.cloud.stream.binding.StreamListenerMessageHandler@7e71340b received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=eb9eea5a-627b-87cc-3ef8-c89ccf487a6c, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=application/json;charset=UTF-8, timestamp=1495942924612}]
2017-05-28 11:42:05.643 DEBUG 26956 --- [RyggHsJiu82Dg-1] actMessageChannelBinder$ReceivingHandler : org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler@699c51ec received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=3a1a1523-634d-6435-d974-02b616897e52, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=text/plain, originalContentType=application/json;charset=UTF-8, timestamp=1495942925643}]
2017-05-28 11:42:05.644 DEBUG 26956 --- [RyggHsJiu82Dg-1] .DispatchingStreamListenerMessageHandler : org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler@75e9086b received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=b303148e-d000-a0c8-3b80-e4a19bc01e5b, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=application/json;charset=UTF-8, timestamp=1495942925643}]
2017-05-28 11:42:05.644 DEBUG 26956 --- [RyggHsJiu82Dg-1] o.s.c.s.b.StreamListenerMessageHandler   : org.springframework.cloud.stream.binding.StreamListenerMessageHandler@7e71340b received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=b303148e-d000-a0c8-3b80-e4a19bc01e5b, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=application/json;charset=UTF-8, timestamp=1495942925643}]
2017-05-28 11:42:07.645 DEBUG 26956 --- [RyggHsJiu82Dg-1] actMessageChannelBinder$ReceivingHandler : org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler@699c51ec received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=5db3a5d3-0393-2bd0-f6f2-d48b8ef3f58f, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=text/plain, originalContentType=application/json;charset=UTF-8, timestamp=1495942927645}]
2017-05-28 11:42:07.645 DEBUG 26956 --- [RyggHsJiu82Dg-1] .DispatchingStreamListenerMessageHandler : org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler@75e9086b received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=ed3e5509-7738-9f0f-ff4a-54f20df0b358, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=application/json;charset=UTF-8, timestamp=1495942927645}]
2017-05-28 11:42:07.645 DEBUG 26956 --- [RyggHsJiu82Dg-1] o.s.c.s.b.StreamListenerMessageHandler   : org.springframework.cloud.stream.binding.StreamListenerMessageHandler@7e71340b received message: GenericMessage [payload={"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedRoutingKey=springCloudBus, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, amqp_consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg, amqp_redelivered=false, id=ed3e5509-7738-9f0f-ff4a-54f20df0b358, amqp_consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, contentType=application/json;charset=UTF-8, timestamp=1495942927645}]
2017-05-28 11:42:07.652  WARN 26956 --- [RyggHsJiu82Dg-1] o.s.a.r.r.RejectAndDontRequeueRecoverer  : Retries exhausted for message (Body:'{"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}' MessageProperties [headers={contentType=text/plain, originalContentType=application/json;charset=UTF-8}, timestamp=null, messageId=null, userId=null, receivedUserId=null, appId=null, clusterId=null, type=null, correlationId=null, correlationIdString=null, replyTo=null, contentType=text/plain, contentEncoding=null, contentLength=0, deliveryMode=null, receivedDeliveryMode=PERSISTENT, expiration=null, priority=0, redelivered=false, receivedExchange=springCloudBus, receivedRoutingKey=springCloudBus, receivedDelay=null, deliveryTag=1, messageCount=0, consumerTag=amq.ctag-iDfCsEiP-9ghHnMxjrSd1w, consumerQueue=springCloudBus.anonymous.YQ_cvHKEQRyggHsJiu82Dg])

org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:876) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:786) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:706) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:96) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:187) ~[spring-rabbit-1.7.1.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_73]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91) ~[spring-retry-1.2.0.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:286) [spring-retry-1.2.0.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:179) [spring-retry-1.2.0.RELEASE.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:115) [spring-retry-1.2.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.sun.proxy.$Proxy175.invokeListener(Unknown Source) [na:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1274) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:687) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1217) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1187) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:96) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1414) [spring-rabbit-1.7.1.RELEASE.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_73]
Caused by: org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Could not resolve type id 'RefreshRemoteApplicationEvent' into a subtype of [simple type, class org.springframework.cloud.bus.event.RemoteApplicationEvent]: known type ids = [RemoteApplicationEvent]
 at [Source: {"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}; line: 1, column: 9]; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'RefreshRemoteApplicationEvent' into a subtype of [simple type, class org.springframework.cloud.bus.event.RemoteApplicationEvent]: known type ids = [RemoteApplicationEvent]
 at [Source: {"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}; line: 1, column: 9]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:224) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:175) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:67) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:67) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.annotation.support.PayloadArgumentResolver.resolveArgument(PayloadArgumentResolver.java:135) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:112) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:135) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:107) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:48) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler$ConditionalStreamListenerHandler.handleMessage(DispatchingStreamListenerMessageHandler.java:122) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler.handleRequestMessage(DispatchingStreamListenerMessageHandler.java:75) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:292) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:212) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:129) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:171) ~[spring-integration-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$400(AmqpInboundChannelAdapter.java:45) ~[spring-integration-amqp-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$1.onMessage(AmqpInboundChannelAdapter.java:95) ~[spring-integration-amqp-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:783) [spring-rabbit-1.7.1.RELEASE.jar:na]
	... 24 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'RefreshRemoteApplicationEvent' into a subtype of [simple type, class org.springframework.cloud.bus.event.RemoteApplicationEvent]: known type ids = [RemoteApplicationEvent]
 at [Source: {"type":"RefreshRemoteApplicationEvent","timestamp":1495942924571,"originService":"config:native:8888","destinationService":"janus:**","id":"8849a798-58b5-4310-a8ff-69d9dd0ad61d"}; line: 1, column: 9]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:42) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeIdException(DeserializationContext.java:1477) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1170) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:282) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:112) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880) ~[jackson-databind-2.8.7.jar:2.8.7]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:219) ~[spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 61 common frames omitted

```

spring-cloud-dependencies version: Dalston.SR1
Among of the dependencies included
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		
		<!-- Web Sockets -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
		</dependency>
	    <dependency>
	      <groupId>org.springframework.boot</groupId>
	      <artifactId>spring-boot-starter-websocket</artifactId>
	    </dependency>

		
		<dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-net</artifactId>
        </dependency>
			
		<dependency>
			<groupId>org.projectreactor</groupId>
			<artifactId>reactor-tcp</artifactId>
			<version>1.0.0.RELEASE</version>
		</dependency>

        <!-- Auto refreshing configuration -->
 		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-amqp</artifactId>
		</dependency> 
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
```

**Comment by spencergibb** [comment]
Any chance you can provide a sample that recreates the problem?

**Comment by lhwong** [comment]
I created a project on github at https://github.com/lhwong/config-websocket

**Comment by spencergibb** [comment]
I think this may be solved by https://github.com/spring-cloud/spring-cloud-bus/issues/74, can you update and see?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
