### ISSUE TITLE
Cloud config + Eureka Server + Hystrix Dashboard - not working

### ISSUE THREAD

**Issue by hamzaame** [spring-cloud/spring-cloud-config#750]
I am creating a webapp which acts as Cloud Config , Eureka Server and a hystrix dashboard.
Config server and Eureka server works fine. But when I try to load hystrix dashboard with url

http://localhost:9080/config-server/hystrix/

I see 404 error on hystrix-logo.png and 500 error on jquery.min.js

I think this line 
```
<script src="/config-server/webjars/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
```

is behaving like accessing the properties file in a config server and it is trying to fetch from the git repository and failing with below error
```
Caused by: org.eclipse.jgit.api.errors.RefNotFoundException: Ref 2.1.1 can not be resolved
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:251) ~[org.eclipse.jgit-4.6.0.201612231935-r.jar:4.6.0.201612231935-r]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.checkout(JGitEnvironmentRepository.java:263) ~[spring-cloud-config-server-1.3.1.RELEASE.jar:1.3.1.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:195) ~[spring-cloud-config-server-1.3.1.RELEASE.jar:1.3.1.RELEASE]
        ... 209 common frames omitted
```

When I debug , i see application as 'webjars', profile as 'jquery' and label as '2.1.1'

Can one app be both config server and a hystrix dashboard? If it can be then please help me resolving this issue.

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

You need to set `spring.cloud.config.server.prefix` to something non-empty, otherwise it is the root of the context.

**Comment by hamzaame** [comment]
Thank you spencer. It works now after adding that property.
