### ISSUE TITLE
quickstart spring-cloud-config-server "../mvnw spring-boot:run" fails to start

### ISSUE THREAD

**Issue by ccheetham** [spring-cloud/spring-cloud-config#819]
Per README, running `../mvnw spring-boot:run` should start a local config server. 

e362f392850fa2ffc3e97f9a147e3e3a6771c71d appears to have broken

```
% git status
HEAD detached at e362f39
nothing to commit, working tree clean

% ../mvnw spring-boot:run
Running version check
The found version is [1.4.0.BUILD-SNAPSHOT]
Deactivating "milestone" profile for version="1.4.0.BUILD-SNAPSHOT"
Deactivating "central" profile for version="1.4.0.BUILD-SNAPSHOT"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-cloud-config-server 1.4.0.BUILD-SNAPSHOT

...<snip>...

***************************
APPLICATION FAILED TO START
***************************

Description:

Cannot determine embedded database driver class for database type NONE

Action:

If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (no profiles are currently active).

[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527)
	at java.lang.Thread.run(Thread.java:748)
<snip>
```

**Comment by superchris** [comment]
Experiencing the same, it would be great to get this up and running!
