### ISSUE TITLE
Error while using git with ssh and not default port.

### ISSUE THREAD

**Issue by Mavlarn** [spring-cloud/spring-cloud-config#852]
I set config server with like:
`uri: ssh://git@git.mydomain.com:3322/my-config-repo.git`
My gitlab server use a different ssh port.

when I request the property, there is an error as below:
```
java.lang.NullPointerException: null
	at com.jcraft.jsch.Session.checkHost(Session.java:802)
	at com.jcraft.jsch.Session.connect(Session.java:342)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1115)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:380)
......
```

After some debug, I find that the following function return null:
```java
      HostKey[] keys = hkr.getHostKey(chost,
                       (key_type.equals("DSA") ? "ssh-dss" : "ssh-rsa"));
```
Which make keys is null and throw exception. If I use default port, removing 3322 from url, it can work.

So how should I config the config server for that? Or how can I fix that.

**Comment by marcingrzejszczak** [comment]
Is the problem still there in Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
