### ISSUE TITLE
Problems with the "label" property using Git as Environment Repository

### ISSUE THREAD

**Issue by michelzanini** [spring-cloud/spring-cloud-config#94]
I created a branch on my config repo in Git with the following name: **1.0.0**.

When I use my Config Server to call:
**http://localhost:8888/app/default/1.0.0**

I get:
```java
org.eclipse.jgit.api.errors.RefNotFoundException: Ref 1.0 can not be resolved
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:244)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.checkout(JGitEnvironmentRepository.java:127)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.loadEnvironment(JGitEnvironmentRepository.java:110)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.findOne(JGitEnvironmentRepository.java:81)
	at org.springframework.cloud.config.server.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:84)
	at org.springframework.cloud.config.server.EnvironmentController.labelled(EnvironmentController.java:62)
```

The problem is that the last value after the last **.** (dot) is ignored.

If I call:
**http://localhost:8888/app/default/1.0.0.0**
It works by fetching my **1.0.0** branch.

There is something there ignoring whatever comes after last dot.

**Comment by dsyer** [comment]
Good catch. No-one tried that before. It's Spring MVC, grrr.
