### ISSUE TITLE
UndeclaredThrowableException when using @RefreshScope in @Service with checked Exceptions in Finchley.M8

### ISSUE THREAD

**Issue by bernieatenovlab** [spring-cloud/spring-cloud-config#949]
I'm using Spring Cloud's `@RefreshScope` annotation within a `@Service` component. This service has a `myTestMethod()` method that throws a checked `MyTestCheckedException`. 

```
@Service
@RefreshScope
public class ExampleServiceImpl implements IExampleService {

    public void myTestMethod() throws MyTestCheckedException {
        throw new MyTestCheckedException("This is a test");
    }

}
```

When calling the `myTestMethod()` from either a unit test or from other classes I get a `UndeclaredThrowableException` instead of the expected `MyTestCheckedException`. 

`MyTestCheckedException` is correctly defined in the `myTestMethod()` signatures inside the interface as well as in the class. 

When I remove the `@RefreshScope` annotation from the service the caller of `myTestMethod()` correctly receives the `MyTestCheckedException` instead of an `UndeclaredThrowableException`. 

A sample project with a Unit Test Case demonstrating the problem can be found at the following link: 
https://github.com/bernieatenovlab/SpringCloudTest

Can you please look why a declared exception gets converted into a UndeclaredThrowableException and possible provide a fix for this?

As a reference the stack trace is: 
```
java.lang.Exception: Unexpected exception, expected<com.example.exceptions.MyTestCheckedException> but was<java.lang.reflect.UndeclaredThrowableException>

	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.UndeclaredThrowableException <<<<< MyTestCheckedException IS NOT AN UndeclaredThrowableException  
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:327)
	at org.springframework.util.ReflectionUtils.handleInvocationTargetException(ReflectionUtils.java:306)
	at org.springframework.util.ReflectionUtils.handleReflectionException(ReflectionUtils.java:290)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:226)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:475)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.example.service.impl.ExampleServiceImpl$$EnhancerBySpringCGLIB$$45e58b70.myTestMethod(<generated>)
	at com.example.ExampleServiceTest.test(ExampleServiceTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 20 more
Caused by: com.example.exceptions.MyTestCheckedException: This is a test
	at com.example.service.impl.ExampleServiceImpl.myTestMethod(ExampleServiceImpl.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
	... 36 more


```

**Comment by spencergibb** [comment]
Refresh scope creates a proxy. You'd have this problem with anything that proxies a bean.

**Comment by bernieatenovlab** [comment]
Hm, doesn't e.g. `@Transactional` create a proxy too? I don't see this issue with `@Transactional` or anywhere else in our code base (`@Cacheable`, etc) ...

**Comment by spencergibb** [comment]
Ok, thanks

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-commons/issues/349
